#ifndef CHDEV_H
#define CHDEV_H
//Не модифицировать вручную!!!

//max 576
enum E_MIL_SUBADDR
{
    BKS1_FROM_IUS,
    BKS1_TO_IUS
};
enum E_MIL_CHANNEL
{
    MIL_IN_RV098_1_OSO_KOU = 3,
    MIL_IN_RV098_2_NVG_KOU = 5,
    MIL_OUT_RV098_1_OSO_OUK = 4,
    MIL_OUT_RV098_2_NVG_OUK = 6,
    MIL_OUT_BINS1_SP2_SA1  = 35,
    MIL_OUT_BINS1_SP2_SA2  = 36,
    MIL_OUT_BINS1_SP2_SA3  = 37,
    MIL_OUT_BINS1_SP2_SA4  = 38,
    MIL_OUT_BINS1_SP2_SA5  = 39,
    MIL_IN_BINS1_SP2_SA1   = 40,
    MIL_IN_BINS1_SP2_SA2   = 41,
    MIL_OUT_BINS2_SP2_SA1  = 42,
    MIL_OUT_BINS2_SP2_SA2  = 43,
    MIL_OUT_BINS2_SP2_SA3  = 44,
    MIL_OUT_BINS2_SP2_SA4  = 45,
    MIL_OUT_BINS2_SP2_SA5  = 46,
    MIL_IN_BINS2_SP2_SA1   = 47,
    MIL_IN_BINS2_SP2_SA2   = 48,
    MIL_OUT_BINS3_SP2_SA1  = 49,
    MIL_OUT_BINS3_SP2_SA2  = 50,
    MIL_OUT_BINS3_SP2_SA3  = 51,
    MIL_OUT_BINS3_SP2_SA4  = 52,
    MIL_OUT_BINS3_SP2_SA5  = 53,
    MIL_IN_BINS3_SP2_SA1   = 54,
    MIL_IN_BINS3_SP2_SA2   = 55,
    MIL_IN_KUTR_R_OSO      = 56,
    MIL_OUT_KUTR_R_OSO     = 57,
    MIL_IN_KUTR_A_NVG      = 58,
    MIL_OUT_KUTR_A_NVG     = 59,
    MIL_OUT_KSU_NVG_SA1    = 60,
    MIL_OUT_KSU_NVG_SA2    = 61,
    MIL_OUT_KSU_NVG_SA3    = 62,
    MIL_IN_KSU_NVG_IN1     = 63,
    MIL_IN_KSU_NVG_IN2     = 64,
    MIL_OUT_KSU_OSO_SA1    = 65,
    MIL_OUT_KSU_OSO_SA2    = 66,
    MIL_OUT_KSU_OSO_SA3    = 67,
    MIL_IN_KSU_OSO_SA1     = 68,
    MIL_IN_KSU_OSO_SA2     = 69,
    MIL_OUT_BSS_OSO_S      = 70,
    MIL_IN_BSS_OSO_S       = 71,
    MIL_OUT_BSS_OSO_D      = 72,
    MIL_IN_BSS_OSO_D       = 73,

    MIL_OUT_BKS1_NVG_SA1   = 315,
    MIL_OUT_BKS1_NVG_SA2   = 165,
    MIL_OUT_BKS1_NVG_SA3   = 166,
    MIL_IN_BKS1_NVG_SA1    = 167,
    MIL_IN_BKS1_NVG_SA2    = 168,
    MIL_OUT_BKS2_OSO_SA1   = 169,
    MIL_OUT_BKS2_OSO_SA2   = 170,
    MIL_OUT_BKS2_OSO_SA3   = 171,
    MIL_IN_BKS2_OSO_SA1    = 172,
    MIL_IN_BKS2_OSO_SA2    = 173,
    MIL_OUT_BKS3_NVG_SA1   = 174,
    MIL_OUT_BKS3_NVG_SA2   = 175,
    MIL_OUT_BKS3_NVG_SA3   = 176,
    MIL_OUT_BKS3_NVG_SA4   = 177,
    MIL_IN_BKS3_NVG_SA1    = 178,
    MIL_IN_BKS3_NVG_SA2    = 179,
    MIL_OUT_BKS4_OSO_SA1   = 180,
    MIL_OUT_BKS4_OSO_SA2   = 181,
    MIL_OUT_BKS4_OSO_SA3   = 182,
    MIL_OUT_BKS4_OSO_SA4   = 183,
    MIL_IN_BKS4_OSO_SA1    = 184,
    MIL_IN_BKS4_OSO_SA2    = 185,
    MIL_IN_CIMSS_A_NVG_SA1 = 316,
    MIL_IN_CIMSS_A_NVG_SA2 = 317,
    MIL_IN_CIMSS_A_NVG_SA3  = 318,
    MIL_IN_CIMSS_A_NVG_SA4  = 319,
    MIL_IN_CIMSS_A_NVG_SA5  = 320,
    MIL_IN_CIMSS_A_NVG_SA6  = 321,
    MIL_IN_CIMSS_A_NVG_SA7  = 322,
    MIL_IN_CIMSS_A_NVG_SA8  = 323,
    MIL_IN_CIMSS_A_NVG_SA9  = 324,
    MIL_IN_CIMSS_A_NVG_SA10 = 325,
    MIL_IN_CIMSS_A_NVG_SA11 = 326,
    MIL_IN_CIMSS_A_NVG_SA12 = 327,
    MIL_IN_CIMSS_A_KSS_SA1  = 328,
    MIL_IN_CIMSS_A_KSS_SA2  = 329,
    MIL_IN_CIMSS_A_KSS_SA3  = 330,
    MIL_IN_CIMSS_A_KSS_SA4  = 331,
    MIL_IN_CIMSS_A_KSS_SA5  = 332,
    MIL_IN_CIMSS_A_KSS_SA6  = 333,
    MIL_IN_CIMSS_A_KSS_SA7  = 334,
    MIL_IN_CIMSS_A_KSS_SA8  = 335,
    MIL_IN_CIMSS_A_KSS_SA9  = 336,
    MIL_IN_CIMSS_A_KSS_SA10 = 337,
    MIL_IN_CIMSS_A_KSS_SA11 = 338,
    MIL_IN_CIMSS_A_KSS_SA12 = 339,
    MIL_OUT_CIMSS_A_NVG_SA1 = 340,
    MIL_OUT_CIMSS_A_NVG_SA2 = 341,
    MIL_OUT_CIMSS_A_NVG_SA3 = 342,
    MIL_OUT_CIMSS_A_NVG_SA4 = 343,

    MIL_OUT_CIMSS_A_KSS_SA1 = 344,
    MIL_OUT_CIMSS_A_KSS_SA2 = 345,
    MIL_OUT_CIMSS_A_KSS_SA3 = 346,
    MIL_OUT_CIMSS_A_KSS_SA4 = 347,

    //! для ЛЛ
    MIL_OUT_BINS1_58_SP2_SA1  = 359,
    MIL_OUT_BINS1_58_SP2_SA2  = 360,
    MIL_OUT_BINS1_58_SP2_SA3  = 361,
    MIL_OUT_BINS1_58_SP2_SA4  = 362,
    MIL_OUT_BINS1_58_SP2_SA5  = 363,
    MIL_IN_BINS1_58_SP2_SA1   = 364,
    MIL_IN_BINS1_58_SP2_SA2   = 365,
    MIL_OUT_BINS2_58_SP2_SA1  = 366,
    MIL_OUT_BINS2_58_SP2_SA2  = 367,
    MIL_OUT_BINS2_58_SP2_SA3  = 368,
    MIL_OUT_BINS2_58_SP2_SA4  = 369,
    MIL_OUT_BINS2_58_SP2_SA5  = 370,
    MIL_IN_BINS2_58_SP2_SA1   = 371,
    MIL_IN_BINS2_58_SP2_SA2   = 372,
    MIL_OUT_RV098_58_NVG_OUK  = 388,
    MIL_IN_RV098_58_NVG_KOU   = 389,

    MIL_OUT_BKS1_58_IUS_SA1 = 390,
    MIL_OUT_BKS1_58_IUS_SA2 = 391,
    MIL_OUT_BKS1_58_IUS_SA3 = 392,
    MIL_OUT_BKS1_58_IUS_SA4 = 393,
    MIL_OUT_BKS1_58_IUS_SA5 = 394,

    MIL_IN_BKS1_58_IUS_SA1    = 395,
    MIL_IN_BKS1_58_IUS_SA2    = 396,
    MIL_IN_BKS1_58_IUS_SA3    = 397,

    MIL_OUT_BKS2_58_NVG_SA1   = 398,
    MIL_OUT_BKS2_58_NVG_SA2   = 399,
    MIL_OUT_BKS2_58_NVG_SA3   = 400,
    MIL_OUT_BKS2_58_NVG_SA4   = 401,
    MIL_OUT_BKS2_58_NVG_SA5   = 402,

    MIL_IN_BKS2_58_NVG_SA1    = 403,
    MIL_IN_BKS2_58_NVG_SA2    = 404,
    MIL_IN_BKS2_58_NVG_SA3    = 405,
    MIL_IN_BKS2_58_NVG_SA4    = 406,

    MIL_OUT_BKS3_58_IUS_SA1   = 407,
    MIL_OUT_BKS3_58_IUS_SA2   = 408,
    MIL_OUT_BKS3_58_IUS_SA3   = 409,
    MIL_OUT_BKS3_58_IUS_SA4   = 410,
    MIL_OUT_BKS3_58_IUS_SA5   = 411,
    MIL_IN_BKS3_58_IUS_SA1    = 412,
    MIL_IN_BKS3_58_IUS_SA2    = 413,
    MIL_IN_BKS3_58_IUS_SA3    = 414,

    MIL_OUT_BKS4_58_NVG_SA1   = 415,
    MIL_OUT_BKS4_58_NVG_SA2   = 416,
    MIL_OUT_BKS4_58_NVG_SA3   = 417,
    MIL_OUT_BKS4_58_NVG_SA4   = 418,
    MIL_IN_BKS4_58_NVG_SA1    = 419,
    MIL_IN_BKS4_58_NVG_SA2    = 420,
    MIL_IN_BKS4_58_NVG_SA3    = 421,

    MIL_IN_RSBN_BNP_58_NVG_SA11 = 422,
    MIL_OUT_RSBN_BNP_58_NVG_SA15 = 423,
    MIL_OUT_RSBN_BNP_58_NVG_SA17 = 424,
    MIL_OUT_RSBN_BNP_58_NVG_SA19 = 425,
    MIL_OUT_RSBN_BNP_58_NVG_SA21 = 426,
    MIL_OUT_RSBN_BNP_58_NVG_SA23 = 427,
    MIL_OUT_RSBN_BNP_58_NVG_SA6  = 428,
    MIL_IN_RSBN_BP_58_NVG_SA12  = 429,
    MIL_OUT_RSBN_BP_58_NVG_SA16  = 430,
    MIL_OUT_RSBN_BP_58_NVG_SA18  = 431,

    MIL_OUT_KSU58_NVG1_SA1          = 432,
    MIL_OUT_KSU58_NVG1_SA2          = 433,
    MIL_OUT_KSU58_NVG1_SA3          = 434,
    MIL_OUT_KSU58_NVG1_SA4          = 435,

    MIL_IN_KSU58_NVG1_IN1           = 436,
    MIL_IN_KSU58_NVG2_IN1           = 437,
    MIL_IN_KSU58_BP1_IN1            = 438,
    MIL_IN_KSU58_BP2_IN1            = 439,

    MIL_OUT_KSU58_NVG2_SA1          = 440,
    MIL_OUT_KSU58_NVG2_SA2          = 441,
    MIL_OUT_KSU58_NVG2_SA3          = 442,
    MIL_OUT_KSU58_NVG2_SA4          = 443,

    MIL_OUT_KSU58_BP1_SA1           = 444,
    MIL_OUT_KSU58_BP1_SA2           = 445,
    MIL_OUT_KSU58_BP1_SA3           = 446,
    MIL_OUT_KSU58_BP1_SA4           = 447,

    MIL_OUT_KSU58_BP2_SA1           = 448,
    MIL_OUT_KSU58_BP2_SA2           = 449,
    MIL_OUT_KSU58_BP2_SA3           = 450,
    MIL_OUT_KSU58_BP2_SA4           = 451,

    MIL_OUT_KUTR58_NVG7_SA2         = 478,
    MIL_OUT_KUTR58_NVG7_SA4         = 479,
    MIL_OUT_KUTR58_NVG8_SA2         = 480,
    MIL_OUT_KUTR58_NVG8_SA4         = 481,
    MIL_OUT_KUTR58_BP1_SA2          = 482,
    MIL_OUT_KUTR58_BP1_SA4          = 483,

    MIL_OUT_BUS_5P                  = 484,
    MIL_OUT_CON_5P                  = 485,
    MIL_OUT_BRPI_5P_SA_15           = 486,
    MIL_OUT_BRPI_5P_SA_1            = 487,
    MIL_OUT_BRPI_5P_SA_2            = 488,
    MIL_OUT_BRPI_5P_SA_3            = 489,
    MIL_OUT_BRPI_5P_SA_4            = 490,
    MIL_OUT_BI_M_1_5P               = 491,
    MIL_OUT_BI_M_2_5P               = 492,
    MIL_OUT_BI_M_3_5P               = 493,
    MIL_OUT_BI_M_4_5P               = 494,
    MIL_OUT_BI_M_5_5P               = 495,
    MIL_OUT_BI_M_6_5P               = 496,
    MIL_OUT_BI_M_9_5P               = 497,
    MIL_OUT_BI_M_10_5P              = 498,
    MIL_OUT_BI_M_11_5P              = 499,
    MIL_OUT_BI_M_12_5P              = 500,

    MIL_OUT_ECR_L_58_S1_NVG         = 542,
    MIL_OUT_ECR_L_58_S2_NVG         = 543,
    MIL_OUT_ECR_L_58_S3_NVG         = 544,
    MIL_OUT_ECR_L_58_S1_BP          = 545,
    MIL_OUT_ECR_L_58_S2_BP          = 546,
    MIL_OUT_ECR_L_58_S3_BP          = 547,
    MIL_OUT_ECR_R_58_S1_NVG         = 548,
    MIL_OUT_ECR_R_58_S2_NVG         = 549,
    MIL_OUT_ECR_R_58_S3_NVG         = 550,
    MIL_OUT_ECR_R_58_S1_BP          = 551,
    MIL_OUT_ECR_R_58_S2_BP          = 552,
    MIL_OUT_ECR_R_58_S3_BP          = 553,

    MIL_OUT_ISRP_58_S1_NVG         = 554,
    MIL_OUT_ISRP_58_S2_NVG         = 555,
    MIL_OUT_ISRP_58_S3_NVG         = 556
};
//! скоростные разовые команды
enum E_SPEED_RK_IN
{

};
enum E_SPEED_RK_OUT
{

};

//! буфер данных для работы с Ethernet расширителем ИОСО.
enum E_ETH_IF_IN
{
    ETH_IP_INSTR,

};
enum E_ETH_IF_OUT
{
    ETH_IP_PKIP         = 25, //обмен с ПКИП стенд 758
    ETH_IP_LMI          = 20, //обмен с лабораторным местом программиста
    ETH_IP_KGOO         = 24, //обмен с комплексом генерации
    ETH_IP_PKIP_58      = 26, //обмен с ПКИП стенд 58
    ETH_IP_ARM_IO       = 27, //обмен с АРМ ИО
    ETH_IP_MLMI         = 34,
    ETH_IP_MLMI_2       = 35,
    ETH_IP_PW           = 36,  //обмен с компьютером управления питания
    ETH_IP_KGOO_2       = 37,
    ETH_IP_KGOO_RMP_1   = 38, //обмен с визуализацией C70
    ETH_IP_KGOO_RMP_2   = 39  //обмен с визуализацией ЛЛ
};

enum E_ETH_PORT
{
    ETH_PORT_SEND_LMI_KGOO   = 0,
    ETH_PORT_REC_LMI_KGOO    = 1,
    ETH_PORT_REC_JOY         = 2,
    ETH_PORT_REC_MPPM        = 3,
    ETH_PORT_JNODE           = 4,
    ETH_PORT_SEND_KGOO_ETH   = 5,
    ETH_PORT_SEND_KGOO_PAL   = 6,
    ETH_PORT_SEND_PKIP       = 7,
    ETH_PORT_REC_PKIP        = 8,
    ETH_PORT_SEND_ARM_IO     = 9,
    ETH_PORT_REC_ARM_IO      = 10,
    ETH_PORT_SEND_PKIP58     = 11,
    ETH_PORT_REC_PKIP58      = 12,
    ETH_PORT_REC_CHECK_HAL   = 13,
    ETH_PORT_SEND_LMI_PW     = 14,
    ETH_PORT_SEND_KGOO_ETH_2 = 15,
    ETH_PORT_SEND_KGOO_RMP_1 = 16,//! рабочее место управления стендом 1
    ETH_PORT_SEND_KGOO_RMP_2 = 17 //! рабочее место управления стендом 2
};
//!номера каналов РК входные
enum E_RK_IN
{
    SVS1_RK_TEST_CONTR = 348,
    SVS1_RK_REZ_CH     = 349,
    SVS1_RK_ISP_AG     = 350,
//    SVS2_RK_TEST_CONTR  ,
//    SVS2_RK_REZ_CH ,
//    SVS2_RK_ISP_AG ,

    SVO_COM_EV1_27V_BKS1  = 452,
    SVO_COM_EV2_27V_BKS4  = 453,
    SVO_COM_EV3_27V_BKS2  = 454,
    SVO_COM_EV3_27V_BKS4  = 455,
    SVO_COM_EV4_27V_BKS2  = 456,
    SVO_COM_EV4_27V_BKS4  = 457,
    SVO_COM_EV5_27V_BKS1  = 458,
    SVO_COM_EV5_27V_BKS2  = 459,
    SVO_COM_EV5_27V_BKS3  = 460,
    SVO_COM_EV5_27V_BKS4  = 461,
    SVO_COM_EV6_27V_BKS1  = 462,
    SVO_COM_EV6_27V_BKS2  = 463,
    SVO_COM_EV6_27V_BKS3  = 464,
    SVO_COM_EV6_27V_BKS4  = 465,

//    TP1_SBROS  ,

    VSU_ZAPUSK_VSU        = 277,//команда запуска ВСУ
    VSU_OSTANOV_VSU       = 278,//команда останова ВСУ

    SPZ_PRESS_ENG_UCOKS1  = 258,
    SPZ_PRESS_ENG_UCOKS2  = 259,
    SPZ_PRESS_ENG_CIMSS_A = 260,

    SPZ_PRESS_VSU_UCOKS1  = 261,
    SPZ_PRESS_VSU_UCOKS2  = 262,
    SPZ_PRESS_VSU_CIMSS_A = 263,

    RK_IN_APDD_1_POWER    = 267,
    RK_IN_APDD_1_VIBOR_VX = 268,
    RK_IN_APDD_2_POWER    = 269,
    RK_IN_APDD_2_VIBOR_VX = 270,

    RK_IN_VIM95_1_POWER   = 271,
    RK_IN_VIM95_1_VKL_A   = 272,
    RK_IN_VIM95_2_VKL_A   = 273,
    RK_IN_VIM95_2_POWER   = 274,

    KSU_SHASS_VIP_REZ1    = 279,
    KSU_SHASS_VIP_REZ2    = 280,
    KSU_SHASS_VIP_REZ3    = 281,
    KSU_SHASS_VIP_REZ4    = 282,

    KSU_AVAR_SHASS_VIP_REZ1 = 283,
    KSU_AVAR_SHASS_VIP_REZ2 = 284,
    KSU_AVAR_SHASS_VIP_REZ3 = 285,
    KSU_AVAR_SHASS_VIP_REZ4 = 286,

    KSU_SHASS_UBOR_REZ1     = 287,
    KSU_SHASS_UBOR_REZ2     = 288,
    KSU_SHASS_UBOR_REZ3     = 289,
    KSU_SHASS_UBOR_REZ4     = 290,

    KSU_AVAR_STV_VIP_REZ1   = 302,
    KSU_AVAR_STV_VIP_REZ2   = 303,
    KSU_AVAR_STV_VIP_REZ3   = 304,
    KSU_AVAR_STV_VIP_REZ4   = 305,
    RK_IN_RUCH_SHASS_58     = 477,
    RK_IN_SUVSH_K_OHL_KOLES = 557,
    RK_IN_UCOKS1_CAB58      = 561,
    RK_IN_UCOKS2_CAB58      = 562,
    RK_IN_AIR_CAB58         = 563,
    RK_IN_RADIO_CAB58       = 564
};
//! номера каналов РК( выходные)
enum E_RK_OUT
{
    SUVSH_KV_ZVP_LOOSH_1         = 74,
    SUVSH_KV_ZVP_LOOSH_2         = 75,
    SUVSH_KV_ZVP_POSH_1          = 76,
    SUVSH_KV_ZVP_POSH_2          = 77,
    SUVSH_KV_ZVP_ROOSH_1         = 78,
    SUVSH_KV_ZVP_ROOSH_2         = 79,
    SUVSH_KV_ZUP_STLOOSH_1       = 80,
    SUVSH_KV_ZUP_STLOOSH_2       = 81,
    SUVSH_KV_ZUP_STROOSH_1       = 82,
    SUVSH_KV_ZUP_STROOSH_2       = 83,
    SUVSH_KV_ZUP_STPOSH_1        = 84,
    SUVSH_KV_ZUP_STPOSH_2        = 85,
    SUVSH_KV_ZUP_POSH_1          = 86,
    SUVSH_KV_ZUP_POSH_2          = 87,
    SUVSH_KV_ZUP_LOOSH_1         = 88,
    SUVSH_KV_ZUP_LOOSH_2         = 89,
    SUVSH_KV_ZUP_ROOSH_1         = 90,
    SUVSH_KV_ZUP_ROOSH_2         = 91,
    SUVSH_KV_ZVP_STROOSH_1       = 92,
    SUVSH_KV_ZVP_STROOSH_2       = 93,
    SUVSH_KV_ZVP_STLOOSH_1       = 94,
    SUVSH_KV_ZVP_STLOOSH_2       = 95,
    SUVSH_KV_ZVP_STPOSH_1        = 96,
    SUVSH_KV_ZVP_STPOSH_2        = 97,
    SUVSH_KONTR_CPEJ_SHASSI_1    = 98,
    SUVSH_KONTR_CPEJ_SHASSI_2    = 99,
    SUVSH_OTKL_OHL_KOLES         = 100,
    SUVSH_RUCH_ST_TORM_OTKL_1    = 351,
    SUVSH_RUCH_ST_TORM_OTKL_2    = 352,

    HPS_ISPR_1GS     = 142,
    HPS_ISPR_1GS_BKS2= 143,
    HPS_ISPR_2GS     = 144,
    HPS_ISPR_2GS_BKS2= 145,
    HPS_ZASOR_FS_1GS = 146,
    HPS_ZASOR_FS_2GS = 147,
    HPS_ZASOR_FNP_1GS= 148,
    HPS_ZASOR_FNP_2GS= 149,
    HPS_ZASOR_FN_1GS = 150,
    HPS_ZASOR_FN_2GS = 151,

    SES_RASTEP_LGSN    = 152,
    SES_OTK_LKANPERI_1 = 153,
    SES_OTK_LKANPERI_2 = 154,
    SES_OTK_RKANPERI_1 = 155,
    SES_OTK_RKANPERI_2 = 156,
    SES_OTKLPRIVGENFID = 157,
    SES_OTKRGENFID     = 158,
    SES_OTK_BRZULEFT   = 159,
    SES_OTK_BRZURIGHT  = 160,
    SES_OTK_1_VU       = 161,
    SES_OTK_2_VU       = 162,
    SES_OTK_3_VU_1     = 163,
    SES_OTK_3_VU_2     = 164,

    SVO_OUT_EV1_BKS1 = 128,
    SVO_OUT_EV2_BKS4 = 129,
    SVO_OUT_EV3_BKS2 = 130,
    SVO_OUT_EV3_BKS4 = 131,
    SVO_OUT_EV4_BKS2 = 132,
    SVO_OUT_EV4_BKS4 = 133,
    SVO_OUT_EV5_BKS1 = 134,
    SVO_OUT_EV5_BKS2 = 135,
    SVO_OUT_EV5_BKS3 = 136,
    SVO_OUT_EV5_BKS4 = 137,
    SVO_OUT_EV6_BKS1 = 138,
    SVO_OUT_EV6_BKS2 = 139,
    SVO_OUT_EV6_BKS3 = 140,
    SVO_OUT_EV6_BKS4 = 141,

    SVS1_RK_ISPR = 264,
    SVS2_RK_ISPR = 265,
    SVS3_RK_ISPR = 266,
//    TP1_NALICH,
//    IKRL_2_ZAPUSK_VSU,//команда запуска ВСУ
//    IKRL_2_OSTANOV_VSU,//команда останова ВСУ

    SPZ_FIRE_ENG_BKS3   = 239,
    SPZ_FIRE_ENG_BKS4   = 240,
    SPZ_FIRE_ENG_PKU_SU = 241,
    SPZ_FIRE_ENG_CIMSS_A= 242,
    SPZ_FIRE_VSU_BKS4   = 243,
    SPZ_FIRE_VSU_BKS3   = 244,
    SPZ_FIRE_VSU_PKU_SU = 245,
    SPZ_FIRE_VSU_CIMSS_A= 246,
    SPZ_GA1_DISARMED_BKS3 = 247,
    SPZ_GA2_DISARMED_BKS4 = 248,
    SPZ_CONTRSPS          = 249,
    SPZ_PK_ENG_CLOSED     = 250,
    SPZ_PK_VSU_CLOSED     = 251,
    SPZ_PK_ENG_OPENED     = 252,
    SPZ_PK_VSU_OPENED     = 253,
    SPZ_PK_OHL_OTKR       = 254,
    SPZ_PK_OHL_ZAKR       = 255,

    SPZ_PRESS_FIRE_ENGINE = 256,
    SPZ_PRESS_FIRE_VSU    = 257,

    //! имитация КВ
    KSU_KV_SHV1         = 102,
    KSU_KV_SHV2         = 103,
    KSU_KV_SHV3         = 104,
    KSU_KV_SHV4         = 105,

    KSU_KV_OPC1         = 106,
    KSU_KV_OPC2         = 107,
    KSU_KV_OPC3         = 108,
    KSU_KV_OPC4         = 109,

    KSU_KV_OGS_L1       = 110,
    KSU_KV_OGS_L2       = 111,

    KSU_KV_OGS_P1       = 112,
    KSU_KV_OGS_P2       = 113,

    KSU_AVAR_PIT1       = 114,
    KSU_AVAR_PIT2       = 115,

    KSU_AEROD_PIT1      = 116,
    KSU_AEROD_PIT2      = 117,

    BPS58_VIP_SHASS_OSN = 118,
    BPS58_UBOR_SHASS_OSN= 119,
    BPS58_VIP_ST_AVAR   = 120,
    BPS58_VIP_SHASS_AVAR= 121,
    KSU_OTKAZ_GS1       = 122,
    KSU_OTKAZ_GS2       = 123,
    KSU_DAV_ST_GS       = 124,
    RV_OTK              = 215,
    RV_VKL              = 216,

    APDDVIM1_OUT_VIBOR_VX= 275,
    APDDVIM2_OUT_VIBOR_VX= 276,

    KSU_OUT_VIP_SHASS_OSN   = 306,
    KSU_OUT_UBOR_SHASS_OSN  = 307,
    KSU_OUT_VIP_STV_AVAR    = 308,
    KSU_OUT_VIP_SH_AVAR     = 309,

    KSU_VKL_DIST_UPR_1K     = 353,
    KSU_VKL_DIST_UPR_2K     = 354,
    KSU_VKL_DIST_UPR_3K     = 355,

    KSU_VIBOR_DIST_UPR      = 356,
    KSU_OBOGREV_HALF        = 357,
    KSU_OBOGREV_FULL        = 358,

    KSU58_AVAR_PIT          = 373,
    KSU58_AEROD_PIT         = 374,
    KSU58_OTKAZ_GS1         = 375,
    KSU58_OTKAZ_GS2         = 376,
    KSU58_DAV_ST_GS         = 377,
    KSU58_OPS_1             = 378,
    KSU58_OPS_2             = 379,
    KSU58_OBJ_OGS_LEV       = 380,
    KSU58_OBJ_OGS_PRAV      = 381,
    KSU58_MRK1              = 382,
    KSU58_FORCE_LEV         = 383,
    KSU58_FORCE_PRAV        = 384,
    KSU58_SHO               = 385,
    KSU58_MRK2              = 386,
    KSU58_VIP_PO            = 387,
    BKO2_ISPR_PVD_L         = 469,
    BKO2_ISPR_DUAS_L        = 470,
    BKO2_ISPR_PVD_R         = 471,
    BKO2_ISPR_DUAS_R        = 472,
    BKO2_FULL_PVD_L         = 473,
    BKO2_FULL_DUAS_L        = 474,
    BKO2_FULL_PVD_R         = 475,
    BKO2_FULL_DUAS_R        = 476,

    KUTR_PPDK_NET               = 530,
    KUTR_OST_750                = 531,
    KUTR_P_ECN73_VSU            = 532,
    KUTR_ZASOR_FM_VSU           = 533,
    KUTR_ZASOR_FM_KSIHT         = 534,
    KUTR_ZASOR_P_K_586200_LEV   = 535,
    KUTR_ZASOR_P_K_586200_PRAV  = 536,
    KUTR_ISPR_KUTR_3            = 537,
    RK_OUT_SUVSH_SHASS_UBOR_KSS = 541,
    RK_OUT_PR_STEND_KSS         = 575

};
enum E_ADC
{
    KSU_AG,
    SVS_PDZ
};
enum E_DAC
{
    SVO_DD1 = 224,
    SVO_DD2 = 225,
    SVO_DD3 = 226,
    SVO_DD4 = 227,

    SVO_DD_BCVM_BKS1   = 228,
    SVO_DD_BCVM_BKS2   = 229,
    SVO_DD_BCVM_BKS3   = 230,
    SVO_DD_BCVM_BKS4   = 231,

    SVO_DD_BKS1   = 232,
    SVO_DD_BKS2   = 233,
    SVO_DD_BKS3   = 234,
    SVO_DD_BKS4   = 235,
    SVO_K_VKL_EV5 = 236,
    SVO_K_VKL_EV6 = 237,
    SVO_RUCH_EV3_4 = 238,

    HPS_P_1GS         = 194,
    HPS_P_1GS_BKS     = 195,
    HPS_P_2GS         = 196,
    HPS_P_2GS_BKS     = 197,
    HPS_P_GA_1GS      = 198,
    HPS_P_GA_2GS      = 199,

    HPS_P_PNEV        = 200,
    HPS_P_PNEV_BKS2   = 201,

    SES_OSN_SHIN      = 310,
    SES_LEV_SHIN1     = 311,
    SES_LEV_SHIN2     = 312,
    SES_PRAV_SHIN1    = 313,
    SES_PRAV_SHIN2    = 314
};
//! каналы имитаторов сопротивлений
enum E_T
{
    SVO_DT1 = 217,
    SVO_DT2 = 218,
    SVO_DT3 = 219,
    SVO_DT4 = 220,
    SVO_DT5 = 221,
    SVO_DT6 = 222,
    SVO_DT7 = 223,

    HPS_TRJ_1GS         = 186,
    HPS_TRJ_1GS_BKS2    = 187,
    HPS_TRJ_2GS         = 188,
    HPS_TRJ_2GS_BKS2    = 189,
    HPS_PERSHT_1GS      = 190,
    HPS_PERSHT_1GS_BKS2 = 191,
    HPS_PERSHT_2GS      = 192,
    HPS_PERSHT_2GS_BKS2 = 193,
    SVS_P_104_1         = 559,
    SVS_P_104_2         = 560
};
enum E_3_PHASE_VOLT
{

    SES_FAZA_A_L = 205,
    SES_FAZA_B_L = 206,
    SES_FAZA_C_L = 207,
    SES_FAZA_A_R = 208,
    SES_FAZA_B_R = 209,
    SES_FAZA_C_R = 210,
    SAU_117_FREQ_N = 538

};
//! каналы термопар
enum E_THERMOCOUPLE
{
    SES_I_VU1 = 202,
    SES_I_VU2 = 203,
    SES_I_VU3 = 204
};

enum E_ARINC_OUT
{
    AR_OUT_SVS1             = 2,
    AR_OUT_SVS2             = 9,
    AR_OUT_SVS3             = 101,

    AR_OUT_VIM95_1_KSU      = 10,
    AR_OUT_VIM95_1_BCVM     = 16,

    AR_OUT_VIM95_2_KSU      = 11,
    AR_OUT_VIM95_2_BCVM     = 17,

    AR_OUT_BSS117_S_BCVM_2  = 33,
    AR_OUT_BSS117_S_SH1L_1  = 566,
    AR_OUT_BSS117_S_SH2L_3  = 567,
    AR_OUT_BSS117_S_UCOKS_1 = 568,
    AR_OUT_BSS117_S_UBRP    = 570,
    AR_OUT_BSS117_S_CIMSS   = 569,
    AR_OUT_BSS117_S_KARP    = 558,
    AR_OUT_BSS117_D_BCVM_1  = 34,
    AR_OUT_BSS117_D_SH1L_2  = 571,
    AR_OUT_BSS117_D_SH2P_4  = 466,
    AR_OUT_BSS117_D_UCOKS_2 = 467,
    AR_OUT_BSS117_D_KARP    = 468,

    AR_OUT_APDD_1_LAND_BCVM = 27,
    AR_OUT_APDD_1_LAND_KSU  = 26,
    AR_OUT_APDD_1_NAV_BCVM  = 22,
    AR_OUT_APDD_1_NAV_KSU   = 24,

    AR_OUT_APDD_2_LAND_BCVM = 28,
    AR_OUT_APDD_2_LAND_KSU  = 29,
    AR_OUT_APDD_2_NAV_BCVM  = 23,
    AR_OUT_APDD_2_NAV_KSU   = 25,

    AR_OUT_RV098_1          = 7,
    AR_OUT_RV098_2          = 8,

    AR_OUT_VSU_UCOKS        = 31,
    AR_OUT_VSU_BKS3         = 32,
    AR_OUT_KUTR             = 30,
    AR_OUT_BINS1            = 125,
    AR_OUT_BINS2            = 126,
    AR_OUT_BINS3            = 127,
    AR_OUT_KSU_L_UCOKS1        = 211,
    AR_OUT_BKS2_KSU         = 213,
    AR_OUT_BKS1_KSU         = 214,
    AR_OUT_KUTR_BKS         = 292,
    AR_OUT_BKS1_KSS         = 293,
    AR_OUT_BKS2_KSS         = 294,
    AR_OUT_BKS3_KSS         = 295,
    AR_OUT_BKS4_KSS         = 296,
    AR_OUT_KSU_L_UCOKS2       = 297,
    AR_OUT_KSU_R_UCOKS1       = 298,
    AR_OUT_KSU_R_UCOKS2       = 299,
    AR_OUT_IKRL_1_1_BCVM      = 501,
    AR_OUT_IKRL_1_2_BCVM      = 502,
    AR_OUT_IKRL_2_1_BCVM      = 503,
    AR_OUT_IKRL_2_2_BCVM      = 506,
    AR_OUT_IKRL_1_KSU_1       = 507,
    AR_OUT_IKRL_1_KSU_3       = 508,
    AR_OUT_IKRL_2_KSU_2       = 509,
    AR_OUT_IKRL_2_KSU_4       = 510,
    AR_OUT_ARK_58             = 516,
    AR_OUT_CO2010             = 519,
    AR_OUT_APDD_58_1_LAND_BCVM = 520,
    AR_OUT_APDD_58_1_LAND_KSU  = 521,
    AR_OUT_APDD_58_1_NAV_BCVM  = 522,
    AR_OUT_APDD_58_1_NAV_KSU   = 523,
    AR_OUT_BINS1_58            = 524,
    AR_OUT_BINS2_58            = 528,
    AR_OUT_BINS1_KSU_58        = 539,
    AR_OUT_BINS2_KSU_58        = 540,
    AR_OUT_KUTR_KSU            = 572,            
    AR_OUT_KUTR_CIMSS          = 573,
    AR_OUT_KUTR_KSS            = 574
};

enum E_ARINC_IN
{
    AR_IN_VIM95_1_BCVM     = 12,
    AR_IN_VIM95_1_UCOKS    = 13,

    AR_IN_VIM95_2_BCVM     = 14,
    AR_IN_VIM95_2_UCOKS    = 15,

    AR_IN_APDD_1_BCVM      = 18,
    AR_IN_APDD_2_BCVM      = 20,
    AR_IN_APDD_1_UCOKS     = 19,
    AR_IN_APDD_2_UCOKS     = 21,
    AR_IN_BKS3_VSU         = 212,
    AR_IN_KSU_UCOKS1       = 291,
    AR_IN_BKS4_KUTR        = 300,
    AR_IN_KSU_UCOKS2       = 301,
    AR_IN_KSU_CIMSS        = 504,
    AR_IN_IKRL_1_BCVM      = 505,
    AR_IN_IKRL_2_BCVM      = 511,
    AR_IN_IKRL_1_BKS1      = 512,
    AR_IN_IKRL_1_BKS3      = 513,
    AR_IN_IKRL_2_BKS2      = 514,
    AR_IN_IKRL_2_BKS4      = 515,
    AR_IN_IKRL_1_KSU       = 517,
    AR_IN_ARK_58           = 518,
    AR_IN_APDD_58_1_BCVM   = 525,
    AR_IN_APDD_58_1_UCOKS  = 526,
    AR_IN_KSU_SBI_58       = 527,
    AR_IN_KSU_SBI          = 529,
    AR_IN_CO2010           = 565

};

//! список параметров
enum P_PARAM
{
    P_NO_PARAM              ,
    P_RV_H                  ,
    P_RV_HV                 ,
    P_RV_SIGMAV             ,
    P_RV_PR_ISP_INFO        ,
    P_RV_PR_ISP_RV          ,
    P_RV_PR_ISP_AFU         ,
    P_RV_PR_ISP_PP          ,
    P_RV_PR_REG_RAB         ,
    P_RV_PR_REG_RM          ,
    P_RV_PR_REG_CNTRL       ,
    P_RV_PR_REG_MEMR        ,
    P_RV_PR_REG_RAB_BCVM    ,
    P_RV_PR_REG_RAM_BCVM    ,
    P_RV_PR_REG_CNTRL_BCVM  ,
    P_SVS_H_ABS             ,
    P_SVS_H_OTN             ,
    P_SVS_VPR               ,
    P_SVS_VIST              ,
    P_SVS_MACH              ,
    P_SVS_VY                ,
    P_SVS_TN                ,
    P_SVS_DHG               ,
    P_SVS_DHB               ,
    P_SVS_DM                ,
    P_SVS_DVPR              ,
    P_SVS_HG                ,
    P_SVS_PZ                ,
    P_SVS_KS                ,
    P_SVS_DOST_H_ABS        ,
    P_SVS_DOST_H_OTN        ,
    P_SVS_DOST_VPR          ,
    P_SVS_DOST_VIST         ,
    P_SVS_DOST_MACH         ,
    P_SVS_DOST_VY           ,
    P_SVS_DOST_TN           ,
    P_SVS_DOST_DHG          ,
    P_SVS_DOST_DHB          ,
    P_SVS_DOST_DM           ,
    P_SVS_DOST_DVPR         ,
    P_SVS_DOST_HG           ,
    P_SVS_DOST_PZ           ,
    //БИНС ПВ01
    P_BINS_ROLL_I_B1        ,
    P_BINS_PITCH_I_B1       ,
    P_BINS_HDG_I_B1         ,
    P_BINS_AX_B1            ,
    P_BINS_AZ_B1            ,
    P_BINS_AY_B1            ,
    P_BINS_OMEGA_X_B1       ,
    P_BINS_OMEGA_Z_B1       ,
    P_BINS_OMEGA_Y_B1       ,
    P_BINS_VNI_B1           ,
    P_BINS_VEI_B1           ,
    P_BINS_VHBI_B1          ,
    P_BINS_BI_B1            ,
    P_BINS_LI_B1            ,
    P_BINS_HBI_B1           ,
    P_BINS_HDGM_I_B1        ,
    P_BINS_DELTA_M_B1       ,
    P_BINS_T_WORK_B1        ,
    P_BINS_SS1_B1_MC1D1     ,
    P_BINS_TZAD1_B1         ,
    P_BINS_DOST_USKOR_B1    ,
    P_BINS_DOST_OMEGA_B1    ,
    P_BINS_DOST_VERTIK_I_B1 ,
    P_BINS_DOST_HDG_I_B1    ,
    P_BINS_DOST_HDGM_I_B1   ,
    P_BINS_DOST_DELTA_M_B1  ,
    P_BINS_DOST_SKOR_I_B1   ,
    P_BINS_DOST_KOORD_I_B1  ,
    P_BINS_DOST_HBI_B1      ,
    P_BINS_DOST_TR_B1       ,
    P_BINS_DOST_H_BAR_B1    ,
    P_BINS_REGIM_RAB_B1     ,
    P_BINS_PR_READY_B1      ,
    P_BINS_TEST_B1          ,
    P_BINS_TYPE_SK_B1       ,
    P_BINS_KOR_B1           ,
    P_BINS_OTKAZ_B1         ,
    P_BINS_INS_B1           ,
    P_BINS_SNS_B1           ,

    //БИНС ПВ02
    P_BINS_SS2_B1_MC1       ,
    P_BINS_SD2_B1_MC1       ,
    P_BINS_VNSNS1_B1_MC1    ,
    P_BINS_VESNS1_B1_MC1    ,
    P_BINS_VHSNS1_B1_MC1    ,
    P_BINS_BSNS_B1_MC1      ,
    P_BINS_LSNS_B1_MC1      ,
    P_BINS_HSNS_B1_MC1      ,
    P_BINS_TSNS_H_B1        ,
    P_BINS_TSNS_M_B1        ,
    P_BINS_TSNS_S_B1        ,
    P_BINS_TS_EXACT_B1      ,
    P_BINS_DATSNS_YEAR_B1   ,
    P_BINS_DATSNS_MONTH_B1  ,
    P_BINS_DATSNS_DAY_B1    ,
    P_BINS_GF_B1            ,
    P_BINS_NLGN_B1          ,
    P_BINS_NGPS_B1          ,
    P_BINS_ERRORRPU_GPS_B1  ,


    //БИНС ПВ03
    P_BINS_DOST_VERT_K_B1       ,
    P_BINS_DOST_HDG_K_B1        ,
    P_BINS_DOST_HDGM_K_B1       ,
    P_BINS_DOST_SKOR_K_B1       ,
    P_BINS_DOST_KOOR_K_B1       ,
    P_BINS_DOST_HK_B1           ,
    P_BINS_DOST_SIGMA_B1        ,
    P_BINS_DOST_VERT_SKOR_K_B1  ,
    P_BINS_ROLL_K_B1_MC1D1      ,
    P_BINS_PITCH_K_B1_MC1D1     ,
    P_BINS_HDG_K_B1_MC1D1       ,
    P_BINS_HDGM_K_B1_MC1D1      ,
    P_BINS_VNK_B1_MC1D1         ,
    P_BINS_VEK_B1_MC1D1         ,
    P_BINS_VHK_B1_MC1           ,
    P_BINS_BK_B1_MC1D1          ,
    P_BINS_LK_B1_MC1D1          ,
    P_BINS_HK_B1_MC1D1          ,

    //БИНС ПВ04
    P_BINS_SKO_B1               ,
    //БИНС ПВ05
    P_BINS_DOST_WK_B1           ,
    P_BINS_DOST_PU_B1           ,
    P_BINS_DOST_PUMAG_B1        ,
    P_BINS_DOST_ATR_B1          ,
    P_BINS_DOST_AG_B1           ,
    P_BINS_DOST_UTR_B1          ,
    P_BINS_DOST_V_VERT_B1       ,
    P_BINS_DOST_U_B1            ,
    P_BINS_DOST_UV_B1           ,
    P_BINS_DOST_OMEGA_PI_B1     ,
    P_BINS_DOST_US_B1           ,
    P_BINS_DOST_UPLF_B1         ,
    P_BINS_WK_B1_MC1                ,
    P_BINS_PU_B1_MC1                ,
    P_BINS_PUM_B1_MC1               ,
    P_BINS_ATR_B1_MC1               ,
    P_BINS_AG_B1_MC1                ,
    P_BINS_UG_TR_B1_MC1             ,
    P_BINS_VY_POT_B1_MC1            ,
    P_BINS_U_B1_MC1                 ,
    P_BINS_UG_V_B1_MC1              ,
    P_BINS_OMEGA_PU_B1_MC1          ,
    P_BINS_US_B1_MC1                ,
    P_BINS_UG_PLF_B1_MC1            ,
    P_BINS_NPMO_B1_MC1              ,

    //КСУ 1
    P_KSU_H_ABS                 ,
    P_KSU_H_ABS_MAT             ,
    P_KSU_V_PR                  ,
    P_KSU_V_PR_MAT              ,
    P_KSU_V_IST                 ,
    P_KSU_V_IST_MAT             ,
    P_KSU_M                     ,
    P_KSU_M_MAT                 ,
    P_KSU_VY                    ,
    P_KSU_VY_MAT                ,
    P_KSU_H_OTN                 ,
    P_KSU_H_OTN_MAT             ,
    P_KSU_PABS                  ,
    P_KSU_PDIF                  ,
    P_KSU_P_Z                   ,
    P_KSU_P_Z_MAT               ,

    P_KSU_TN                    ,
    P_KSU_TT                    ,
    P_KSU_ALFA_IST              ,
    P_KSU_ALFA_IST_MAT          ,
    P_KSU_BETA_IST              ,
    P_KSU_BETA_IST_MAT          ,
    P_KSU_ALFA_MAX              ,
    P_KSU_ALFA_MAX_MAT          ,
    P_KSU_ALFA_MIN              ,
    P_KSU_ALFA_MIN_MAT          ,
    P_KSU_BETA_DOP              ,
    P_KSU_BETA_DOP_MAT          ,
    P_KSU_NY_MAX                ,
    P_KSU_NY_MAX_MAT            ,
    P_KSU_NY_MIN                ,
    P_KSU_NY_MIN_MAT            ,
    P_KSU_V_MAX                 ,
    P_KSU_V_MAX_MAT             ,
    P_KSU_V_MIN                 ,
    P_KSU_V_MIN_MAT             ,
    P_KSU_M_DOP                 ,
    P_KSU_M_DOP_MAT             ,
    P_KSU_SRK1                  ,
    P_KSU_SRK1_MAT              ,
    P_KSU_SRK2                  ,
    P_KSU_SRK2_MAT              ,
    P_KSU_SRK3                  ,
    P_KSU_SRK3_MAT              ,
    P_KSU_SRK14                 ,
    P_KSU_SRK14_MAT             ,
    P_KSU_SRK51                 ,
    P_KSU_SRK52                 ,
    //! КСУ 2
    P_KSU_N_Y                   ,
    P_KSU_N_Y_MAT               ,
    P_KSU_N_Z                   ,
    P_KSU_N_Z_MAT               ,
    P_KSU_N_X                   ,
    P_KSU_OMEGA_X               ,
    P_KSU_OMEGA_Y               ,
    P_KSU_OMEGA_Z               ,
    P_KSU_XTET                  ,
    P_KSU_XTET_MAT                  ,
    P_KSU_XGAMM                 ,
    P_KSU_XGAMM_MAT                 ,
    P_KSU_XP                    ,
    P_KSU_XP_MAT                    ,
    P_KSU_CPVO_LEV              ,
    P_KSU_CPVO_PRAV             ,
    P_KSU_FLL                   ,
    P_KSU_FLP                   ,
    P_KSU_STABL                 ,
    P_KSU_STABP                 ,


    P_KSU_NAPL_LEV              ,
    P_KSU_NAPL_PRAV             ,

    P_KSU_NOS_LEV               ,
    P_KSU_NOS_PRAV              ,

    P_KSU_EL_LEV                ,
    P_KSU_EL_PRAV               ,

    P_KSU_PS_LEV                ,
    P_KSU_PS_PRAV               ,

    P_KSU_H_BEZ                 ,
    P_KSU_NY_RASP_DOP           ,
    P_KSU_ALF_RUD               ,
    P_KSU_ALF_RUD_MAT           ,
    P_KSU_XTPL                  ,
    P_KSU_XTPR                  ,
    P_KSU_ELEV_VN_LEV           ,
    P_KSU_ELEV_VN_PRAV          ,
    P_KSU_SR_LEV                ,
    P_KSU_SR_PRAV               ,
    P_KSU_VNES_H_LEV            ,
    P_KSU_VNES_H_PRAV           ,
    P_KSU_INT_LEV               ,
    P_KSU_INT_PRAV              ,
    P_KSU_SRK4                  ,
    P_KSU_SRK4_MAT              ,
    P_KSU_SRK5                  ,
    P_KSU_SRK5_MAT              ,
    P_KSU_SRK7                  ,
    P_KSU_SRK7_MAT              ,
    P_KSU_SRK9                  ,
    P_KSU_SRK18                 ,
    P_KSU_SRK19                 ,
    P_KSU_SRK15                 ,
    P_KSU_SRK16                 ,
    P_KSU_SRK17                 ,
    P_KSU_SRK21                 ,
    P_KSU_SRK22                 ,

    P_KSU_SRK8                  ,
    P_KSU_SRK8_MAT              ,
    P_KSU_SRK53                 ,
    P_KSU_SRK54                 ,

    //ксу 3
    P_KSU_DIR_PROD              ,
    P_KSU_DIR_PROD_MAT          ,
    P_KSU_DIR_KREN              ,
    P_KSU_DIR_KREN_MAT          ,
    P_KSU_V_ZAD_PRIB            ,
    P_KSU_OTKL_GAMMA_ZAD        ,
    P_KSU_OTKL_NY_ZAD           ,
    P_KSU_OTKL_VZAD             ,
    P_KSU_D_PSI                 ,
    P_KSU_D_H                   ,
    P_KSU_RUD_SR                ,
    P_KSU_FI_T                  ,
    P_KSU_FI_K                  ,
    P_KSU_FI_RUD                ,
    P_KSU_D_FI_RUD              ,
    P_KSU_ALFA_RUD_P            ,
    P_KSU_ALFA_RUD_L            ,
    P_KSU_GAMMA_ZAD_SAU         ,
    P_KSU_NY_ZAD_SAU            ,
    P_KSU_HSOS                  ,
    P_KSU_TETA_TRAEK            ,
    P_COUNT_KSU                 ,
    P_KSU_UPR_AUT               ,
    P_KSU_KOD_FROM_KSU          ,
    P_KSU_D11                   ,
    P_KSU_D11_MAT               ,
    P_KSU_D21                   ,
    P_KSU_D21_MAT               ,
    P_KSU_D12                   ,
    P_KSU_D12_MAT               ,
    P_KSU_D22                   ,
    P_KSU_D22_MAT               ,
    P_KSU_D_POSH                ,
    P_KSU_VRULEG                ,
    P_KSU_XTPL_INT              ,
    P_KSU_XTPR_INT              ,
    P_KSU_CNT_ISPR_KSU          ,
    P_KSU_SRK10                 ,
    P_KSU_SRK10_MAT             ,
    P_KSU_SRK11                 ,
    P_KSU_SRK11_MAT             ,
    P_KSU_SRK12                 ,
    P_KSU_SRK12_MAT             ,
    P_KSU_SRK55                 ,
    P_KSU_SRK56                 ,
    P_KSU_SRK57                 ,
    P_KSU_SRK58                 ,
    P_KSU_SRK59                 ,
    P_KSU_SRK60                 ,
    P_KSU_SRK61                 ,
    //BCVM
    P_KSU_D_OBR_VPP             ,
    P_KSU_L_VPP                 ,
    P_KSU_H_AER                 ,
    P_KSU_PSI_VPP               ,
    P_KSU_D_VPP                 ,
    P_KSU_FI_AER                ,
    P_KSU_LM_AER                ,
    P_KSU_LM_G_PR               ,
    P_KSU_LM_G_OBR              ,
    P_KSU_H_KR                  ,
    P_KSU_H_RV1                 ,
    P_KSU_H_RV2                 ,
    P_KSU_SKO_KOORD             ,
    P_KSU_SRK13                 ,
    P_KSU_SRK13_MAT             ,
    //BCVM2
    P_KSU_FI_OT1_PR             ,
    P_KSU_LM_OT1_PR             ,
    P_KSU_FI_OT2_PR             ,
    P_KSU_LM_OT2_PR             ,
    P_KSU_FI_OT1_OBR            ,
    P_KSU_LM_OT1_OBR            ,
    P_KSU_FI_OT2_OBR            ,
    P_KSU_LM_OT2_OBR            ,
    P_KSU_H_OT1_PR              ,
    P_KSU_H_OT2_PR              ,
    P_KSU_H_OT1_OBR             ,
    P_KSU_H_OT2_OBR             ,
    P_KSU_SRK6                  ,
    P_KSU_EPS_G                 ,
    P_KSU_EPS_G_MAT             ,
    P_KSU_EPS_K                 ,
    P_KSU_EPS_K_MAT             ,
    P_KSU_P760                  ,
    P_KSU_P760_MAT              ,

    //P_KSU_SRK7                  ,
    P_KSU_RV_H                  ,
    P_KSU_RV_H_MAT              ,
    P_KSU_KREN                  ,
    P_KSU_KREN_MAT              ,
    P_KSU_TAN                   ,
    P_KSU_TAN_MAT               ,
    P_KSU_FI_SENI               ,
    P_KSU_FI_SENI_MAT           ,
    P_KSU_LAM_SENI              ,
    P_KSU_LAM_SENI_MAT          ,
    //P_KSU_P_Z                   ,
    P_RV_PRISPAFU               ,
    P_RV_MAT_HRV                ,

    //ксу 4
    P_KSU_DELTA_RUD_RAZN        ,
    P_KSU_WHY_ERR_PRIV          ,
    P_KSU_WHY_ERR_PRIV_NUM      ,
    P_KSU_SRK30                 ,
    P_KSU_SRK31                 ,
    P_KSU_SRK32                 ,
    P_KSU_SRK33                 ,
    P_KSU_SRK34                 ,
    P_KSU_SRK35                 ,
    P_KSU_SRK36                 ,
    P_KSU_SRK37                 ,
    P_KSU_SRK38                 ,
    P_KSU_SRK39                 ,
    P_KSU_SRK40                 ,
    P_KSU_SRK41                 ,
    P_KSU_SRK42                 ,
    P_KSU_SRK43                 ,
    P_KSU_SRK44                 ,
    P_KSU_SRK45                 ,
    P_KSU_SRK46                 ,
    P_KSU_SRK47                 ,
    P_KSU_SRK01_70              ,

    // КСУ СБИ 58
    P_KSU_X_PED                 ,
    P_KSU_X_PED_MAT             ,
    P_KSU_XTPLINT               ,
    P_KSU_XTPLINT_MAT           ,
    P_KSU_XTPRINT               ,
    P_KSU_XTPRINT_MAT           ,
    P_KSU_X_TAN                 ,
    P_KSU_X_TAN_MAT             ,
    P_KSU_X_GAMMA               ,
    P_KSU_X_GAMMA_MAT           ,
    P_KSU_P_BRAKE_L_SS1         ,
    P_KSU_P_BRAKE_L_SS1_MAT     ,
    P_KSU_P_BRAKE_R_SS1         ,
    P_KSU_P_BRAKE_R_SS1_MAT     ,
    P_KSU_P_BRAKE_L_SS2         ,
    P_KSU_P_BRAKE_L_SS2_MAT     ,
    P_KSU_P_BRAKE_R_SS2         ,
    P_KSU_P_BRAKE_R_SS2_MAT     ,
    P_KSU_D_MRK                 ,
    P_KSU_D_MRK_MAT             ,
    P_KSU_ALPHA_MAX_DOP         ,
    P_KSU_ALPHA_MAX_DOP_MAT     ,
    P_KSU_ALPHA_MIN_DOP         ,
    P_KSU_ALPHA_MIN_DOP_MAT     ,
    P_KSU_NY_MAX_DOP            ,
    P_KSU_NY_MAX_DOP_MAT        ,
    P_KSU_NY_MIN_DOP            ,
    P_KSU_NY_MIN_DOP_MAT        ,
    P_KSU_BETA_MAX_DOP          ,
    P_KSU_BETA_MAX_DOP_MAT      ,
    P_KSU_ALFA_RUD_PRAV         ,
    P_KSU_ALFA_RUD_PRAV_MAT     ,
    P_KSU_ALFA_RUD_LEV          ,
    P_KSU_ALFA_RUD_LEV_MAT      ,
    P_KSU_ALFA_RUD_SR           ,
    P_KSU_ALFA_RUD_SR_MAT       ,
    P_KSU_UPR_PROD              ,
    P_KSU_UPR_PROD_MAT          ,
    P_KSU_UPR_BOK               ,
    P_KSU_UPR_BOK_MAT           ,
    P_KSU_DNY_SAU               ,
    P_KSU_DNY_SAU_MAT           ,
    P_KSU_SBI_SRK3              ,
    P_KSU_SBI_SRK3_MAT          ,
    P_KSU_SBI_SRK5              ,
    P_KSU_SBI_SRK5_MAT          ,
    P_KSU_X_TAN_NPU             ,
    P_KSU_X_TAN_MAT_NPU         ,
    P_KSU_X_GAMMA_NPU           ,
    P_KSU_X_GAMMA_MAT_NPU       ,
    P_KSU_X_PED_NPU             ,
    P_KSU_X_PED_MAT_NPU         ,
    P_KSU_ALFA_RUD_SR_NPU       ,
    P_KSU_ALFA_RUD_SR_MAT_NPU   ,
    P_KSU_XTPLINT_NPU           ,
    P_KSU_XTPLINT_MAT_NPU       ,
    P_KSU_XTPRINT_NPU           ,
    P_KSU_XTPRINT_MAT_NPU       ,
    P_VDU_SRK17                 ,


    //!ВСУ
    P_VSU_KSL1                  ,
    P_VSU_KSL2                  ,
    P_VSU_SBIX1                 ,
    P_VSU_SBIX2                 ,
    P_VSU_DCR                   ,
    P_VSU_DCSKD                 ,
    P_VSU_DCKU                  ,
    P_VSU_SBX1                  ,
    P_VSU_SBX2                  ,
    P_VSU_SBX3                  ,
    P_VSU_SOO                   ,
    P_VSU_SOU                   ,
    P_VSU_SOFU1                 ,
    P_VSU_SOFU2                 ,
    P_VSU_SOFU3                 ,
    P_VSU_SSUPIT                ,
    P_VSU_SOLD                  ,
    P_VSU_CPO                   ,
    P_VSU_NAGR                  ,
    P_VSU_NDVIG                 ,



    P_VSU_NTK                   ,
    P_VSU_MC_NTK                ,
    P_VSU_NTK1                  ,
    P_VSU_MC_NTK1               ,
    P_VSU_NTK2                  ,
    P_VSU_MC_NTK2               ,
    P_VSU_TG                    ,
    P_VSU_MC_TG                 ,
    P_VSU_TG1                   ,
    P_VSU_MC_TG1                ,
    P_VSU_TG2                   ,
    P_VSU_MC_TG2                ,
    P_VSU_TGX                   ,
    P_VSU_MC_TGX                ,

    P_VSU_TM                    ,
    P_VSU_MC_TM                 ,

    P_VSU_PMF                   ,
    P_VSU_MC_PMF                ,
    P_VSU_PMN                   ,
    P_VSU_MC_PMN                ,
    P_VSU_PT                    ,
    P_VSU_MC_PT                 ,
    P_VSU_TAGR                  ,
    P_VSU_MC_TAGR               ,
    P_VSU_GT                    ,
    P_VSU_MC_GT                 ,
    P_VSU_TGS                   ,
    P_VSU_MC_TGS                ,
    P_VSU_NARERRD               ,
    P_VSU_MC_NARERRD            ,
    P_VSU_NARAPU               ,
    P_VSU_MC_NARAPU            ,
    P_VSU_KOLZAP               ,
    P_VSU_MC_KOLZAP            ,
    P_VSU_TZAP               ,
    P_VSU_MC_TZAP            ,

    P_VSU_TGOGR               ,
    P_VSU_MC_TGOGR            ,
    P_VSU_TGZASCH               ,
    P_VSU_MC_TGZASCH            ,
    P_VSU_YGT               ,
    P_VSU_MC_YGT            ,
    P_VSU_IGT               ,
    P_VSU_MC_IGT            ,
    P_VSU_UGT               ,
    P_VSU_MC_UGT            ,
    P_VSU_UPIT               ,
    P_VSU_MC_UPIT            ,
    P_VSU_U10               ,
    P_VSU_MC_U10            ,
    P_VSU_NTKZ               ,
    P_VSU_MC_NTKZ            ,
    P_VSU_DNTKZ               ,
    P_VSU_MC_DNTKZ            ,
    P_VSU_NTKS               ,
    P_VSU_MC_NTKS            ,
    P_VSU_GTZ               ,
    P_VSU_MC_GTZ            ,
    P_VSU_TVIB               ,
    P_VSU_MC_TVIB            ,
    P_VSU_NEISPR1               ,
    P_VSU_MC_NEISPR1            ,
    P_VSU_NARDV1               ,
    P_VSU_MC_NARDV1            ,
    P_VSU_KOLZAP1               ,
    P_VSU_MC_KOLZAP1            ,
    P_VSU_NARDV2            ,
    P_VSU_MC_NARDV2            ,
    P_VSU_MC_NEISPR2,
    P_VSU_NEISPR2,
    P_VSU_KOLZAP2               ,
    P_VSU_MC_KOLZAP2            ,
    P_VSU_NEISPRP3              ,
    P_VSU_MC_NEISPRP3           ,
    P_VSU_NARDV3            ,
    P_VSU_MC_NARDV3            ,
    P_VSU_KOLZAP3               ,
    P_VSU_MC_KOLZAP3            ,
    P_VSU_NEISPRP4              ,
    P_VSU_MC_NEISPRP4           ,
    P_VSU_NARDV4            ,
    P_VSU_MC_NARDV4            ,
    P_VSU_KOLZAP4               ,
    P_VSU_MC_KOLZAP4            ,
    P_VSU_NARDV5            ,
    P_VSU_MC_NARDV5            ,
    P_VSU_KOLZAP5               ,
    P_VSU_MC_KOLZAP5            ,
    P_VSU_NEISPRP               ,
    P_VSU_MC_NEISPRP            ,
    P_VSU_NEISPRP5              ,
    P_VSU_MC_NEISPRP5           ,




    P_VSU_B_FIRE                ,
    //P_VSU_SBX3                  ,

    //! fazlov
    P_BINS_CY1                  ,
    P_BINS_CY2                  ,
    P_BINS_CD2                  ,

    P_BINS_FI_IN                ,
    P_BINS_LAMBDA_IN            ,
    P_BINS_HOURB                ,
    P_BINS_MINB                 ,
    P_BINS_SECB                 ,
    P_BINS_DATB                 ,
    P_BINS_ALGWORDS_0           ,
    P_BINS_ALGWORDS_1           ,
    P_BINS_ALGWORDS_2           ,
    P_BINS_ALGWORDS_3           ,
    P_BINS_ALGWORDS_4           ,
    P_BINS_ALGWORDS_5           ,

    P_KUTR_G_RSUM               ,
    P_KUTR_Q                    ,
    P_KUTR_M_Q                  ,
    P_KUTR_QPEREP               ,
    P_KUTR_M_QPEREP             ,
    P_KUTR_TTOP_PDK             ,
    P_KUTR_TTOP_PEREP           ,
    P_KUTR_TTOP_B1              ,
    P_KUTR_P1_TOP_B1            ,
    P_KUTR_G_TSUM_IND           ,
    P_KUTR_G_TB1                ,
    P_KUTR_SRK1                 ,
    P_KUTR_SRK2                 ,
    P_KUTR_SRK3                 ,
    P_KUTR_SRK4                 ,

    //VIM
    P_VIM_WORK_VOR_ILS              ,
    P_VIM_FREQ_VOR_ILS_0_01_MHZ     ,
    P_VIM_FREQ_VOR_ILS_0_1_MHZ      ,
    P_VIM_FREQ_VOR_ILS_1_MHZ        ,
    P_VIM_FREQ_VOR_ILS_10_MHZ       ,
    P_VIM_MAT034                    ,

    P_VIM_WORK_ILS_CP50             ,
    P_VIM_FREQ_ILS_0_01_MHZ         ,
    P_VIM_FREQ_ILS_0_1_MHZ          ,
    P_VIM_FREQ_ILS_1_MHZ            ,
    P_VIM_FREQ_ILS_10_MHZ           ,
    P_VIM_MAT033                    ,

    P_VIM_ZAP_PER1                  ,
    P_VIM_EK                        ,
    P_BIM_MAT_EK                    ,
    P_VIM_ZAP_PER2                  ,
    P_VIM_EG                        ,
    P_VIM_MAT_EG                    ,
    P_VIM_STS                       ,
    P_VIM_MAT_STS                   ,
//ПВ04
    P_BINS_TZAD1_B1_MC1D3           ,
    P_BINS_SS1_B1_MC1D3             ,
    P_BINS_SD4_B1_MC1               ,

    P_BINS_ROLL_I_B1_MC1D2          ,
    P_BINS_PITCH_I_B1_MC1D2         ,
    P_BINS_HDG_I_B1_MC1D2           ,

    P_BINS_VNI_B1_MC1D2             ,
    P_BINS_VEI_B1_MC1D2             ,
    P_BINS_VHBI_B1_MC1D2            ,

    P_BINS_OMEGA_X_B1_MC1D2         ,
    P_BINS_OMEGA_Z_B1_MC1D2         ,
    P_BINS_OMEGA_Y_B1_MC1D2         ,

    P_BINS_ROLL_K_B1_MC1D2          ,
    P_BINS_PITCH_K_B1_MC1D2         ,
    P_BINS_HDG_K_B1_MC1D2           ,

    P_BINS_VNK_B1_MC1D2             ,
    P_BINS_VEK_B1_MC1D2             ,
    P_BINS_VHBIK_B1_MC1D2           ,

    P_BINS_T_ZAD2_B1_MC1            ,

    P_BINS_BK_B1_MC1D2              ,
    P_BINS_LK_B1_MC1D2              ,
    P_BINS_HK_B1_MC1D2              ,

    P_BINS_SKO_B1_MC1               ,
//пв05
    P_BINS_SS1_B1_MC1D4             ,
    P_BINS_SD5_B1_MC1               ,
//пв03
    P_BINS_SS1_B1_MC1D2             ,
    P_BINS_SD3_B1_MC1               ,
//пв02
    //naim
    P_BINS_DATSNS                   ,

    //пв01

    P_BKS1_KSU_W360                 ,
    P_BINS_SD1_B1_MC1               ,
    P_APDD_PSI_VPP_180_IN           ,
    P_APDD_NUM_CH_GLS_IN            , //-
    P_APDD_CH_GLS_HI                ,
    P_APDD_CH_GLS_LOW               ,
    P_APDD_SEL_REGIME               ,
    P_APDD_NAV_NUM_SP_S_S           ,
    P_APDD_NAV_NUM_SP_S_S_MAT       ,
    P_APDD_NAV_MSL                  ,
    P_APDD_NAV_MSL_MAT              ,
    P_APDD_NAV_HDOP                 ,
    P_APDD_NAV_HDOP_MAT             ,
    P_APDD_NAV_VDOP                 ,
    P_APDD_NAV_VDOP_MAT             ,
    P_APDD_NAV_PUT_UGOL_IST         ,
    P_APDD_NAV_PUT_UGOL_IST_MAT     ,
    P_APDD_NAV_FI_SENL              ,
    P_APDD_NAV_FI_SENL_MAT          ,
    P_APDD_NAV_LAM_SENL             ,
    P_APDD_NAV_LAM_SENL_MAT         ,
    P_APDD_NAV_W                    ,
    P_APDD_NAV_W_MAT                ,
    P_APDD_NAV_FI                   ,
    P_APDD_NAV_FI_MAT               ,
    P_APDD_NAV_LAM                  ,
    P_APDD_NAV_LAM_MAT              ,
    P_APDD_NAV_HIL                  ,
    P_APDD_NAV_HIL_MAT              ,
    P_APDD_NAV_VIL                  ,
    P_APDD_NAV_VIL_MAT              ,
    P_APDD_NAV_VFOM                 ,
    P_APDD_NAV_VFOM_MAT             ,
    P_APDD_NAV_VERT_V               ,
    P_APDD_NAV_VERT_V_MAT           ,
    P_APDD_NAV_PR_W_S_U             ,
    P_APDD_NAV_PR_W_S_U_MAT         ,
    P_APDD_NAV_PR_W_Z_W             ,
    P_APDD_NAV_PR_W_Z_W_MAT         ,
    P_APDD_NAV_HFOM                 ,
    P_APDD_NAV_HFOM_MAT             ,
    P_APDD_NAV_PRM_GNSS             ,
    P_APDD_NAV_PRM_GNSS_MAT         ,
    P_APDD_NAV_GNSS_OTKAZ           ,
    P_APDD_NAV_GNSS_OTKAZ_MAT       ,
    P_APDD_NAV_H_WGS_84             ,
    P_APDD_NAV_H_WGS_84_MAT         ,
    P_APDD_PSI_VPP_180              ,
    P_APDD_PSI_VPP_180_MAT          ,
    P_APDD_PSI_VPP_360              ,
    P_APDD_PSI_VPP_360_MAT          ,
    P_APDD_N_CH_GLS_MAT             ,
    P_APDD_LAND_EK_FUT              ,
    P_APDD_LAND_EK_FUT_MAT          ,
    P_APDD_LAND_EG_FUT              ,
    P_APDD_LAND_EG_FUT_MAT          ,

    P_APDD_LAND_N_ISKL_SP_1         ,
    P_APDD_LAND_N_ISKL_SP_1_MAT     ,
    P_APDD_LAND_N_ISKL_SP_2         ,
    P_APDD_LAND_N_ISKL_SP_2_MAT     ,
    P_APDD_LAND_FOM_VERT            ,
    P_APDD_LAND_FOM_VERT_MAT        ,
    P_APDD_LAND_HIL                 ,
    P_APDD_LAND_HIL_MAT             ,
    P_APDD_LAND_VIL                 ,
    P_APDD_LAND_VIL_MAT             ,
    P_APDD_LAND_FOM_GOR             ,
    P_APDD_LAND_FOM_GOR_MAT         ,
    //P_APDD_LAND_FOM_VERT,
    P_APDD_LAND_ZAP_EK              ,
    P_APDD_LAND_ILS_GLS_EK          ,
    P_APDD_LAND_EK_RGM              ,
    P_APDD_LAND_EK_MAT              ,

    P_APDD_LAND_ZAP_EG              ,
    P_APDD_LAND_ILS_GLS_EG          ,
    P_APDD_LAND_EG_RGM              ,
    P_APDD_LAND_EG_MAT              ,

    P_APDD_LAND_D_VPP_GOR           ,
    P_APDD_LAND_D_VPP_GOR_MAT       ,
    P_APDD_LAND_SS                  ,
    P_APDD_LAND_SS_MAT              ,
    P_APDD_MAT_033                  ,

    //! БКС1->БЦВМ
    BKS1_BCVM_SDS_1_1               ,
    BKS1_BCVM_SDS_2_1               ,
    BKS1_BCVM_SDS_3_1               ,
    BKS1_BCVM_SDS_4_1               ,
    BKS1_BCVM_U_fazaA_left          ,
    BKS1_BCVM_D_U_fazaA_left        ,
    BKS1_BCVM_U_fazaB_left          ,
    BKS1_BCVM_D_U_fazaB_left        ,
    BKS1_BCVM_U_fazaC_left          ,
    BKS1_BCVM_D_U_fazaC_left        ,
    BKS1_BCVM_f_LkanPer_I           ,
    BKS1_BCVM_D_f_LkanPer_I         ,
    BKS1_BCVM_U_osn_shin            ,
    BKS1_BCVM_D_U_osn_shin          ,
    BKS1_BCVM_U_leftav_shin_1       ,
    BKS1_BCVM_D_U_leftav_shin_1     ,
    BKS1_BCVM_U_rightav_shin_1      ,
    BKS1_BCVM_D_U_rightav_shin_1    ,
    BKS1_BCVM_I_VU1                 ,
    BKS1_BCVM_D_I_VU1               ,
    BKS1_BCVM_T1_SVO                ,
    BKS1_BCVM_D_T1_SVO              ,
    BKS1_BCVM_T2_LB                 ,
    BKS1_BCVM_D_T2_LB               ,
    BKS1_BCVM_T4_SES                ,
    BKS1_BCVM_D_T4_SES              ,
    BKS1_BCVM_DD1_1                 ,
    BKS1_BCVM_D_DD1_1               ,
    BKS1_BCVM_DD3_1                 ,
    BKS1_BCVM_D_DD3_1               ,
    BKS1_BCVM_S_S_BKS_1             ,
    BKS1_BCVM_K_NK_BKS1             ,
    BKS1_BCVM_MVI_SS_1              ,
    BKS1_BCVM_MPA_SS_1              ,
    BKS1_BCVM_MPA_SS1_1             ,
    BKS1_BCVM_MPA_SS2_1             ,
    BKS1_BCVM_MSK_SS_1              ,
    BKS1_BCVM_Operating_Time_1      ,
    BKS1_BCVM_SJS_BKS_1             ,
    BKS1_BCVM_KS_1                  ,
    BKS1_BCVM_SDZU_1                ,
    BKS1_BCVM_TIMER_START_1         ,
    BKS1_BCVM_TIMER_STOP_1          ,
    BKS1_BCVM_K_SCU_1_1             ,
    BKS1_BCVM_SCB_1                 ,
    //! БЦВМ -> БКС1
    BCVM_BKS1_SCU_1_1               ,
    BCVM_BKS1_SCU_2_1               ,
    BCVM_BKS1_SCU_3_1               ,
    BCVM_BKS1_SCU_4_1               ,
    BCVM_BKS1_SCU_5_1               ,


    //! БКС2->БЦВМ
    P_BKS2_BCVM_SDS_1_2                    ,
    P_BKS2_BCVM_SDS_2_2                    ,
    P_BKS2_BCVM_SDS_3_2                    ,
    P_BKS2_BCVM_T3_PRB                     ,
    P_BKS2_BCVM_D_T3_PRB                   ,
    P_BKS2_BCVM_T5_SP56                    ,
    P_BKS2_BCVM_D_T5_SP56                  ,
    P_BKS2_BCVM_DD2_2                      ,
    P_BKS2_BCVM_D_DD2_2                    ,
    P_BKS2_BCVM_DD3_2                      ,
    P_BKS2_BCVM_D_DD3_2                    ,
    P_BKS2_BCVM_U_fazaA_right              ,
    P_BKS2_BCVM_D_U_fazaA_right            ,
    P_BKS2_BCVM_U_fazaB_right              ,
    P_BKS2_BCVM_D_U_fazaB_right            ,
    P_BKS2_BCVM_U_fazaC_right              ,
    P_BKS2_BCVM_D_U_fazaC_right            ,
    P_BKS2_BCVM_f_RkanPer_I                ,
    P_BKS2_BCVM_D_f_RkanPer_I              ,
    P_BKS2_BCVM_U_leftav_shin_2            ,
    P_BKS2_BCVM_D_U_leftav_shin_2          ,
    P_BKS2_BCVM_U_rightav_shin_2           ,
    P_BKS2_BCVM_D_U_rightav_shin_2         ,
    P_BKS2_BCVM_I_VU2                      ,
    P_BKS2_BCVM_D_I_VU2                    ,
    P_BKS2_BCVM_I_VU3                      ,
    P_BKS2_BCVM_D_I_VU3                    ,
    P_BKS2_BCVM_S_S_BKS_2                  ,
    P_BKS2_BCVM_K_NK_BKS2                  ,
    P_BKS2_BCVM_MVI_SS_2                   ,
    P_BKS2_BCVM_MPA_SS_2                   ,
    P_BKS2_BCVM_MPA_SS1_2                  ,
    P_BKS2_BCVM_MPA_SS2_2                  ,
    P_BKS2_BCVM_MSK_SS_2                   ,
    P_BKS2_BCVM_Operating_Time_2           ,
    P_BKS2_BCVM_SJS_BKS_2                  ,
    P_BKS2_BCVM_KS_2                       ,
    P_BKS2_BCVM_SDZU_2                     ,

    P_BKS2_BCVM_TIMESTART_2                ,
    P_BKS2_BCVM_TIMESTOP_2                 ,
    P_BKS2_BCVM_SCB2                       ,
    P_BKS2_BCVM_K_SCU_1_2                  ,

    BCVM_BKS2_SCU_1_2                      ,
    BCVM_BKS2_SCU_2_2                      ,
    BCVM_BKS2_SCU_3_2                      ,
    BCVM_BKS2_SCU_4_2                      ,
    BCVM_BKS2_SCU_5_2                      ,
    //! БКС3->БЦВМ
    //!
    P_BKS3_BCVM_P_1GS                   ,
    P_BKS3_BCVM_D_P_1GS                 ,
    P_BKS3_BCVM_P_2GS                   ,
    P_BKS3_BCVM_D_P_2GS                 ,
    P_BKS3_BCVM_P_GA_1GS                ,
    P_BKS3_BCVM_D_P_GA_1GS              ,
    P_BKS3_BCVM_PerSht_1GS              ,
    P_BKS3_BCVM_D_PerSht_1GS            ,
    P_BKS3_BCVM_PerSht_2GS              ,
    P_BKS3_BCVM_D_PerSht_2GS            ,
    P_BKS3_BCVM_P_pnev                  ,
    P_BKS3_BCVM_D_P_pnev                ,
    P_BKS3_BCVM_Trj_1GS                 ,
    P_BKS3_BCVM_D_Trj_1GS               ,
    P_BKS3_BCVM_Trj_2GS                 ,
    P_BKS3_BCVM_D_Trj_2GS               ,
    P_BKS3_BCVM_ObK_Pup_D               ,
    P_BKS3_BCVM_D_ObK_Pup_D             ,
    P_BKS3_BCVM_Tgasturb_D              ,
    P_BKS3_BCVM_D_Tgasturb_D            ,
    P_BKS3_BCVM_T7_EV4                  ,
    P_BKS3_BCVM_D_T7_EV4                ,
    P_BKS3_BCVM_DD1_3                   ,
    P_BKS3_BCVM_D_DD1_3                 ,
    P_BKS3_BCVM_DD4_3                   ,
    P_BKS3_BCVM_D_DD4_3                 ,

    P_BKS3_BCVM_SDS_1_3                 ,
    P_BKS3_BCVM_SDS_2_3                 ,
    P_BKS3_BCVM_SDS_3_3                 ,
    P_BKS3_BCVM_SDS_4_3                 ,
    //! подадрес
    P_BKS3_BCVM_SDS_5_3                 ,
    P_BKS3_BCVM_S_S_BKS_3               ,
    P_BKS3_BCVM_K_NK_BKS3               ,
    P_BKS3_BCVM_MVI_SS_3                ,
    P_BKS3_BCVM_MPA_SS_3                ,
    P_BKS3_BCVM_MPA_SS1_3               ,
    P_BKS3_BCVM_MPA_SS2_3               ,
    P_BKS3_BCVM_MSK_SS_3                ,
    P_BKS3_BCVM_Operating_Time_3        ,
    //! подадрес
    P_BKS3_BCVM_SJS_BKS_3               ,
    P_BKS3_BCVM_KS_3                    ,
    P_BKS3_BCVM_SDZU_3                  ,
    P_BKS3_BCVM_TIMESTART_3             ,
    P_BKS3_BCVM_TIMESTOP_3              ,
    //! подадрес
    P_BKS3_BCVM_SCB3                    ,
    P_BKS3_BCVM_K_SCU_1_3               ,
    P_BKS3_BCVM_SDS_6_3                 ,
    BCVM_BKS3_SCU_1_3                   ,
    BCVM_BKS3_SCU_2_3                   ,
    BCVM_BKS3_SCU_3_3                   ,
    BCVM_BKS3_SCU_4_3                   ,
    BCVM_BKS3_SCU_5_3                   ,
    P_BKS3_KSS_OUT1                     ,
    P_BKS3_KSS_OUT2                     ,
    P_BKS3_KSS_OUT3                     ,
    P_BKS3_KSS_OUT4                     ,
    //! БКС4->БЦВМ
    P_BKS4_BCVM_P_1GS               ,
    P_BKS4_BCVM_D_P_1GS             ,
    P_BKS4_BCVM_P_2GS               ,
    P_BKS4_BCVM_D_P_2GS             ,
    P_BKS4_BCVM_P_GA_2GS            ,
    P_BKS4_BCVM_D_P_GA_2GS          ,
    P_BKS4_BCVM_PerSht_1GS          ,
    P_BKS4_BCVM_D_PerSht_1GS        ,
    P_BKS4_BCVM_PerSht_2GS          ,
    P_BKS4_BCVM_D_PerSht_2GS        ,
    P_BKS4_BCVM_P_pnev              ,
    P_BKS4_BCVM_D_P_pnev            ,
    P_BKS4_BCVM_Trj_1GS             ,
    P_BKS4_BCVM_D_Trj_1GS           ,
    P_BKS4_BCVM_Trj_2GS             ,
    P_BKS4_BCVM_D_Trj_2GS           ,
    P_BKS4_BCVM_T6_NChF             ,
    P_BKS4_BCVM_D_T6_NChF           ,
    P_BKS4_BCVM_DD2_4               ,
    P_BKS4_BCVM_D_DD2_4             ,
    P_BKS4_BCVM_DD4_4               ,
    P_BKS4_BCVM_D_DD4_4             ,
    P_BKS4_BCVM_G_Rsum              ,
    P_BKS4_BCVM_Q                   ,
    P_BKS4_BCVM_M_Q                 ,
    P_BKS4_BCVM_Qperep              ,
    P_BKS4_BCVM_M_Qperep            ,
    P_BKS4_BCVM_Ttop_pdk            ,
    P_BKS4_BCVM_Ttop_perep          ,
    P_BKS4_BCVM_Ttop_B1             ,
    P_BKS4_BCVM_Pl_top_B1           ,
    P_BKS4_BCVM_G_Tsum_ind          ,
    P_BKS4_BCVM_G_TB1               ,

    P_BKS4_BCVM_SDS_1_4             ,
    P_BKS4_BCVM_SDS_2_4             ,
    P_BKS4_BCVM_SDS_3_4             ,
    P_BKS4_BCVM_SDS_4_4             ,
    P_BKS4_BCVM_SDS_5_4             ,
    P_BKS4_BCVM_SDS_6_4             ,

    P_BKS4_BCVM_S_S_BKS_4           ,
    P_BKS4_BCVM_K_NK_BKS4           ,

    P_BKS4_BCVM_MVI_SS_4            ,
    P_BKS4_BCVM_MPA_SS_4            ,
    P_BKS4_BCVM_MPA_SS1_4           ,
    P_BKS4_BCVM_MPA_SS2_4           ,
    P_BKS4_BCVM_MSK_SS_4            ,
    P_BKS4_BCVM_STS_BKS_4           ,
    P_BKS4_BCVM_SJS_BKS_4           ,
    P_BKS4_BCVM_SKS_4               ,
    P_BKS4_BCVM_SDZU_4              ,

    P_BKS4_BCVM_TIMESTART_4         ,
    P_BKS4_BCVM_TIMESTOP_4          ,
    P_BKS4_BCVM_SCB4                ,
    P_BKS4_BCVM_K_SCU_1_4           ,
    P_BKS4_BCVM_SDS_7_4             ,

    P_SAU117_N2F                    ,
    P_SAU117_D_N2F                  ,
    P_SAU117_T4COR                  ,
    P_SAU117_D_T4                   ,
    P_SAU117_T4COR_MAX              ,
    P_SAU117_D_T4COR_MAX              ,
    P_SAU117_STEP                   ,
    P_SAU117_D_STEP                 ,
    P_SAU117_SDS_1                  ,
    P_SAU117_D_SDS_1                 ,
    P_SAU117_SDS_2                  ,
    P_SAU117_D_SDS_2                 ,
    P_SAU117_SDS_3                  ,
    P_SAU117_D_SDS_3                 ,
    P_SAU117_SDS_4                  ,
    P_SAU117_N1F                    ,
    P_SAU117_D_N1                   ,
    P_SAU117_T1F                    ,
    P_SAU117_D_T1                   ,
    P_SAU117_R_PROG                 ,
    P_SAU117_D_R_PROG               ,
    P_SAU117_RF                     ,
    P_SAU117_D_RF                   ,
    BCVM_BKS4_SCU_1_4               ,
    BCVM_BKS4_SCU_3_4               ,
    BCVM_BKS4_SCU_2_4               ,
    BCVM_BKS4_SCU_4_4               ,
    BCVM_BKS4_SCU_5_4               ,
    CIMSS_A_CISPR                   ,
    CIMSS_A_NUM_PP                  ,
    CIMSS_A_CNT_OBMEN               ,
    CIMSS_A_SOST1                   ,
    CIMSS_A_SOST2                   ,
    CIMSS_A_SOST3                   ,
    CIMSS_A_SOST4                   ,
    CIMSS_A_SOST5                   ,
    CIMSS_A_SOST6                   ,
    CIMSS_A_SOST7                   ,
    CIMSS_A_SOST8                   ,
    CIMSS_A_SOST9                   ,
    CIMSS_A_NUM_BCVM_KSS          ,
    CIMSS_A_MASSIV_1_BCVM_KSS     ,
    CIMSS_A_MASSIV_2_BCVM_KSS     ,
    CIMSS_A_MASSIV_3_BCVM_KSS     ,
    CIMSS_A_MASSIV_4_BCVM_KSS     ,
    CIMSS_A_MASSIV_5_BCVM_KSS     ,
    CIMSS_A_MASSIV_6_BCVM_KSS     ,
    CIMSS_A_MASSIV_7_BCVM_KSS     ,
    CIMSS_A_MASSIV_8_BCVM_KSS     ,
    CIMSS_A_MASSIV_9_BCVM_KSS     ,
    CIMSS_A_MASSIV_10_BCVM_KSS    ,
    CIMSS_A_MASSIV_11_BCVM_KSS    ,
    CIMSS_A_MASSIV_12_BCVM_KSS    ,
    CIMSS_A_MASSIV_13_BCVM_KSS    ,
    CIMSS_A_MASSIV_14_BCVM_KSS    ,
    CIMSS_A_MASSIV_15_BCVM_KSS    ,
    CIMSS_A_MASSIV_16_BCVM_KSS    ,
    CIMSS_A_MASSIV_17_BCVM_KSS    ,
    CIMSS_A_MASSIV_18_BCVM_KSS    ,
    CIMSS_A_MASSIV_19_BCVM_KSS    ,
    CIMSS_A_MASSIV_20_BCVM_KSS    ,
    CIMSS_A_MASSIV_21_BCVM_KSS    ,
    CIMSS_A_MASSIV_22_BCVM_KSS    ,
    CIMSS_A_MASSIV_23_BCVM_KSS    ,
    CIMSS_A_MASSIV_24_BCVM_KSS    ,
    CIMSS_A_MASSIV_25_BCVM_KSS    ,
    CIMSS_A_MASSIV_26_BCVM_KSS    ,
    CIMSS_A_MASSIV_27_BCVM_KSS    ,
    CIMSS_A_MASSIV_28_BCVM_KSS    ,
    CIMSS_A_MASSIV_29_BCVM_KSS    ,
    CIMSS_A_MASSIV_30_BCVM_KSS    ,
    CIMSS_A_MASSIV_31_BCVM_KSS    ,


    P_IKRL1_BKS1_SASBKS1_KSS_Out_1   ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_2   ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_3   ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_4   ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_5   ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_6   ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_7   ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_8   ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_9   ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_10  ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_11  ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_12  ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_13  ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_14  ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_15  ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_16  ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_17  ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_18  ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_19  ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_20  ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_21  ,
    P_IKRL1_BKS1_SASBKS1_KSS_Out_22  ,
    P_IKRL1_BKS1_SDSBKS1_KSS_Out_1   ,
    P_IKRL1_BKS1_SDSBKS1_KSS_Out_2   ,
    P_IKRL1_BKS1_SDSBKS1_KSS_Out_3   ,


    P_IKRL1_BKS3_SASBKS3_KSS_Out_1   ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_2   ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_3   ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_4   ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_5   ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_6   ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_7   ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_8   ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_9   ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_10  ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_11  ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_12  ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_13  ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_14  ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_15  ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_16  ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_17  ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_18  ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_19  ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_20  ,
    P_IKRL1_BKS3_SASBKS3_KSS_Out_21  ,
    P_IKRL1_BKS3_SDSBKS3_KSS_Out_1   ,
    P_IKRL1_BKS3_SDSBKS3_KSS_Out_2   ,
    P_IKRL1_BKS3_SDSBKS3_KSS_Out_3   ,
    P_IKRL1_BKS3_SDSBKS3_KSS_Out_4   ,

    P_IKRL1_BCVM_SINVG_Out_1  ,
    P_IKRL1_BCVM_SINVG_Out_2  ,
    P_IKRL1_BCVM_SINVG_Out_3  ,
    P_IKRL1_BCVM_SINVG_Out_4  ,
    P_IKRL1_BCVM_SINVG_Out_5  ,
    P_IKRL1_BCVM_SINVG_Out_6  ,
    P_IKRL1_BCVM_SINVG_Out_7  ,
    P_IKRL1_BCVM_SINVG_Out_8  ,
    P_IKRL1_BCVM_SINVG_Out_9  ,
    P_IKRL1_BCVM_SINVG_Out_10 ,
    P_IKRL1_BCVM_SINVG_Out_11 ,
    P_IKRL1_BCVM_SINVG_Out_12 ,
    P_IKRL1_BCVM_SINVG_Out_13 ,
    P_IKRL1_BCVM_SINVG_Out_14 ,
    P_IKRL1_BCVM_SINVG_Out_15 ,
    P_IKRL1_BCVM_SINVG_Out_16 ,
    P_IKRL1_BCVM_SINVG_Out_17 ,
    P_IKRL1_BCVM_SINVG_Out_18 ,
    P_IKRL1_BCVM_SINVG_Out_19 ,
    P_IKRL1_BCVM_SINVG_Out_20 ,
    P_IKRL1_BCVM_SINVG_Out_21 ,
    P_IKRL1_BCVM_SINVG_Out_22 ,
    P_IKRL1_BCVM_SINVG_Out_23 ,
    P_IKRL1_BCVM_SINVG_Out_37 ,
    P_IKRL1_BCVM_SINVG_Out_38 ,


    P_IKRL2_BKS2_SASBKS2_KSS_Out_1   ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_2   ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_3   ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_4   ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_5   ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_6   ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_7   ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_8   ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_9   ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_10  ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_11  ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_12  ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_13  ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_14  ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_15  ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_16  ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_17  ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_18  ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_19  ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_20  ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_21  ,
    P_IKRL2_BKS2_SASBKS2_KSS_Out_22  ,
    P_IKRL2_BKS2_SDSBKS2_KSS_Out_1   ,
    P_IKRL2_BKS2_SDSBKS2_KSS_Out_2   ,


    P_IKRL2_BKS4_SASBKS4_KSS_Out_1   ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_2   ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_3   ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_4   ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_5   ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_6   ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_7   ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_8   ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_9   ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_10  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_11  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_12  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_13  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_14  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_15  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_16  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_17  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_18  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_19  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_20  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_21  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_22  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_23  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_24  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_25  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_26  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_27  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_28  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_29  ,
    P_IKRL2_BKS4_SASBKS4_KSS_Out_30  ,
    P_IKRL2_BKS4_SDSBKS4_KSS_Out_1   ,
    P_IKRL2_BKS4_SDSBKS4_KSS_Out_2   ,
    P_IKRL2_BKS4_SDSBKS4_KSS_Out_3   ,
    P_IKRL2_BKS4_SDSBKS4_KSS_Out_4   ,
    P_IKRL2_BKS4_SDSBKS4_KSS_Out_5   ,
    //БИНС ДПК
    P_BINS_AR_CCINA                  ,
    P_BINS_AR_ISP_INS                ,
    P_BINS_AR_SS_B1_BIT_31           ,
    P_BINS_AR_BK_B1                  ,
    P_BINS_AR_BK_B1_BIT_30           ,
    P_BINS_AR_BK_B1_BIT_31           ,
    P_BINS_AR_LK_B1                  ,
    P_BINS_AR_LK_B1_BIT_30           ,
    P_BINS_AR_LK_B1_BIT_31           ,
    P_BINS_AR_WK_B1                  ,
    P_BINS_AR_WK_B1_BIT_30           ,
    P_BINS_AR_WK_B1_BIT_31           ,
    P_BINS_AR_PU_B1                  ,
    P_BINS_AR_PU_B1_BIT_30           ,
    P_BINS_AR_PU_B1_BIT_31           ,
    P_BINS_AR_OMEGA_PU_B1            ,
    P_BINS_AR_OMEGA_PU_B1_BIT_30     ,
    P_BINS_AR_OMEGA_PU_B1_BIT_31     ,
    P_BINS_AR_HDG_I_B1               ,
    P_BINS_AR_HDG_I_BIT_30           ,
    P_BINS_AR_HDG_I_BIT_31           ,
    P_BINS_AR_PUM_I_B1               ,
    P_BINS_AR_PUM_I_BIT_30           ,
    P_BINS_AR_PUM_I_BIT_31           ,
    P_BINS_AR_HDGM_I_B1              ,
    P_BINS_AR_HDGM_I_BIT_30          ,
    P_BINS_AR_HDGM_I_BIT_31          ,

    P_BINS_AR_PITCH_I_B1             ,
    P_BINS_AR_PITCH_I_BIT_30         ,
    P_BINS_AR_PITCH_I_BIT_31         ,
    P_BINS_AR_ROLL_I_B1              ,
    P_BINS_AR_ROLL_I_BIT_30          ,
    P_BINS_AR_ROLL_I_BIT_31          ,
    P_BINS_AR_HDG_GIR_I_B1           ,
    P_BINS_AR_HDG_GIR_I_BIT_30       ,
    P_BINS_AR_HDG_GIR_I_BIT_31       ,
//    P_BINS_AR_OMEGA_Z_I_B1           ,
//    P_BINS_AR_OMEGA_Z_I_BIT_30       ,
//    P_BINS_AR_OMEGA_Z_I_BIT_31       ,

    P_BINS_AR_VNK_B1           ,
    P_BINS_AR_VNK_BIT_30       ,
    P_BINS_AR_VNK_BIT_31       ,

    P_BINS_AR_VEK_B1           ,
    P_BINS_AR_VEK_BIT_30       ,
    P_BINS_AR_VEK_BIT_31       ,

    P_BINS_AR_VHK_B1           ,
    P_BINS_AR_VHK_BIT_30       ,
    P_BINS_AR_VHK_BIT_31       ,

    P_BINS_AR_UG_PLF_B1           ,
    P_BINS_AR_UG_PLF_BIT_30       ,
    P_BINS_AR_UG_PLF_BIT_31       ,

    P_BINS_AR_OMEGA_X_I_B1           ,
    P_BINS_AR_OMEGA_X_I_BIT_30       ,
    P_BINS_AR_OMEGA_X_I_BIT_31       ,

    P_BINS_AR_OMEGA_Y_I_B1           ,
    P_BINS_AR_OMEGA_Y_I_BIT_30       ,
    P_BINS_AR_OMEGA_Y_I_BIT_31       ,

    P_BINS_AR_OMEGA_Z_I_B1           ,
    P_BINS_AR_OMEGA_Z_I_BIT_30       ,
    P_BINS_AR_OMEGA_Z_I_BIT_31       ,
    P_BINS_AR_VY_POT_I_B1            ,
    P_BINS_AR_VY_POT_I_BIT_30        ,
    P_BINS_AR_VY_POT_I_BIT_31        ,

    P_BINS_AR_AX_B1           ,
    P_BINS_AR_AX_BIT_30       ,
    P_BINS_AR_AX_BIT_31       ,

    P_BINS_AR_AY_B1           ,
    P_BINS_AR_AY_BIT_30       ,
    P_BINS_AR_AY_BIT_31       ,
    P_BINS_AR_AZ_B1           ,
    P_BINS_AR_AZ_BIT_30       ,
    P_BINS_AR_AZ_BIT_31       ,
    P_BINS_AR_AG_B1           ,
    P_BINS_AR_AG_BIT_30       ,
    P_BINS_AR_AG_BIT_31       ,

    P_BINS_AR_HBI_I_B1               ,
    P_BINS_AR_HBI_I_BIT_30           ,
    P_BINS_AR_HBI_I_BIT_31           ,
    P_BINS_AR_U_B1                   ,
    P_BINS_AR_U_BIT_30               ,
    P_BINS_AR_U_BIT_31               ,
    P_BINS_AR_UG_V_B1                ,
    P_BINS_AR_UG_V_BIT_30            ,
    P_BINS_AR_UG_V_BIT_31            ,
    P_BINS_AR_US_B1                  ,
    P_BINS_AR_US_BIT_30              ,
    P_BINS_AR_US_BIT_31              ,
    P_BINS_AR_UG_TR_B1               ,
    P_BINS_AR_UG_TR_BIT_30           ,
    P_BINS_AR_UG_TR_BIT_31           ,
    P_BKS1_58_BCVM_SDS_1_1             ,
    //P_BKS1_58_BCVM_SDS_1_1             ,
    P_BKS1_58_BCVM_SDS_3_1             ,
    P_BKS1_58_BCVM_SDS_4_1             ,
    P_BKS1_58_BCVM_SDS_22_1            ,
    P_BKS1_58_BCVM_SDS_23_1            ,
    P_BKS1_58_BCVM_Operating_Time_1    ,
    P_BKS1_58_BCVM_SJS_BKS_1           ,
    P_BKS1_58_BCVM_SDS_2_1             ,
    P_BKS1_58_BCVM_SDS_5_1             ,
    P_BKS1_58_BCVM_SDS_24_1            ,
    P_BKS1_58_BCVM_SSCU_1_1            ,
    P_BKS1_58_BCVM_SSCU_2_1            ,
    P_BKS1_58_BCVM_SDS_25_1            ,
    P_BKS1_58_BCVM_SCB_1               ,
    P_BKS1_58_BCVM_SSCU_3_1            ,
    P_BKS1_58_BCVM_MVI_SS_1            ,
    P_BKS1_58_BCVM_MPA_SS_1            ,
    P_BKS1_58_BCVM_MPA_SS1_1           ,
    P_BKS1_58_BCVM_MPA_SS2_1           ,
    P_BKS1_58_BCVM_MSK_SS_1            ,
    P_BKS1_58_BCVM_KS_1                ,
    P_BKS1_58_BCVM_SDZU_1              ,
    P_BKS1_58_BCVM_TIMER_START_1       ,
    P_BKS1_58_BCVM_TIMER_STOP_1        ,
    P_BKS1_58_BCVM_T_STEKLA1           ,
    P_BKS1_58_BCVM_D_T_STEKLA1           ,
    P_BKS1_58_BCVM_T_STEKLA3           ,
    P_BKS1_58_BCVM_D_T_STEKLA3           ,

    P_BKS1_58_BCVM_U_SEKOB1           ,
    P_BKS1_58_BCVM_D_U_SEKOB1           ,
    P_BKS1_58_BCVM_U_SEKOB2           ,
    P_BKS1_58_BCVM_D_U_SEKOB2           ,
    P_BKS1_58_BCVM_U_SEKOB3           ,
    P_BKS1_58_BCVM_D_U_SEKOB3           ,
    P_BKS1_58_BCVM_P_PNEV           ,
    P_BKS1_58_BCVM_D_P_PNEV           ,
    //P_BKS1_58_BCVM_P_PNEV           ,
    //P_BKS1_58_BCVM_D_P_PNEV           ,

    P_BKS1_58_BCVM_TEKZNA4_PPARZ      ,
    P_BKS1_58_BCVM_D_TEKZNA4_PPARZ    ,

    P_BKS1_58_BCVM_DIHAN_PILOT       ,
    P_BKS1_58_BCVM_D_DIHAN_PILOT     ,
    P_BKS1_58_BCVM_POL_RUD_LD        ,
    P_BKS1_58_BCVM_D_POL_RUD_LD      ,
    P_BKS1_58_BCVM_POL_RUD_RD        ,
    P_BKS1_58_BCVM_D_POL_RUD_RD      ,
    P_BKS1_58_BCVM_TK                ,
    P_BKS1_58_BCVM_D_TK              ,
    P_BKS1_58_BCVM_T2                ,
    P_BKS1_58_BCVM_D_T2              ,
    P_BKS1_58_BCVM_T3                ,
    P_BKS1_58_BCVM_D_T3              ,
    P_BKS1_58_BCVM_TNOS_1            ,
    P_BKS1_58_BCVM_D_TNOS_1          ,
    P_BKS1_58_BCVM_TZAK_1            ,
    P_BKS1_58_BCVM_D_TZAK_1          ,
    P_BKS1_58_BCVM_PGOR_DD1          ,
    P_BKS1_58_BCVM_D_PGOR_DD1        ,
    P_BKS1_58_BCVM_PK_DD4_1          ,
    P_BKS1_58_BCVM_D_PK_DD4_1        ,
    P_BKS1_58_BCVM_U_FAZAA_LEFT      ,
    P_BKS1_58_BCVM_D_U_FAZAA_LEFT    ,
    P_BKS1_58_BCVM_U_FAZAB_LEFT      ,
    P_BKS1_58_BCVM_D_U_FAZAB_LEFT    ,
    P_BKS1_58_BCVM_U_FAZAC_LEFT      ,
    P_BKS1_58_BCVM_D_U_FAZAC_LEFT    ,
    P_BKS1_58_BCVM_F_LKANPER_I       ,
    P_BKS1_58_BCVM_D_F_LKANPER_I     ,
    P_BKS1_58_BCVM_U_OSN_SHIN        ,
    P_BKS1_58_BCVM_D_U_OSN_SHIN      ,
    P_BKS1_58_BCVM_U_LEFTAV_SHIN     ,
    P_BKS1_58_BCVM_D_U_LEFTAV_SHIN   ,
    P_BKS1_58_BCVM_I_VU1             ,
    P_BKS1_58_BCVM_D_I_VU1           ,
    P_BKS1_58_BCVM_FAZI_DIHAN        ,
    P_BKS1_58_BCVM_D_FAZI_DIHAN      ,
    P_BKS1_58_BCVM_ALFA                       ,
    P_BKS1_58_BCVM_D_ALFA                     ,
    P_BKS1_58_BCVM_BETA                       ,
    P_BKS1_58_BCVM_D_BETA                     ,
    P_BKS1_58_BCVM_BKS1_PARTIAL_PRESSURE2     ,
    P_BKS1_58_BCVM_D_BKS1_PARTIAL_PRESSURE2   ,
    P_BKS1_58_BCVM_DPMU_DD6                   ,
    P_BKS1_58_BCVM_D_DPMU_DD6                 ,
    P_BKS1_58_BCVM_DD1_SGO_1                  ,
    P_BKS1_58_BCVM_D_DD1_SGO_1                ,
    P_BKS1_58_BCVM_DD2_SGO_1                  ,
    P_BKS1_58_BCVM_D_DD2_SGO_1                ,


    P_BKS2_58_BCVM_SDS_7_2           ,
    P_BKS2_58_BCVM_SDS_8_2           ,
    P_BKS2_58_BCVM_SDS_9_2           ,
    P_BKS2_58_BCVM_SDS_27_2          ,
    P_BKS2_58_BCVM_SCB_2               ,
    P_BKS2_58_BCVM_MVI_SS_2          ,
    P_BKS2_58_BCVM_MPA_SS_2          ,
    P_BKS2_58_BCVM_MPA_SS1_2         ,
    P_BKS2_58_BCVM_MPA_SS2_2         ,
    P_BKS2_58_BCVM_MSK_SS_2          ,
    P_BKS2_58_BCVM_Operating_Time_2  ,
    P_BKS2_58_BCVM_SJS_BKS_2         ,
    P_BKS2_58_BCVM_KS_2              ,
    P_BKS2_58_BCVM_SDZU_2            ,
    P_BKS2_58_BCVM_TIMESTART_2       ,
    P_BKS2_58_BCVM_TIMESTOP_2        ,

    P_BKS2_58_BCVM_TEKZNA4_PPARZ     ,
    P_BKS2_58_BCVM_D_TEKZNA4_PPARZ   ,
    P_BKS2_58_BCVM_DIHAN_PILOT       ,
    P_BKS2_58_BCVM_D_DIHAN_PILOT     ,
    P_BKS2_58_BCVM_U_FAZAA_RIGHT     ,
    P_BKS2_58_BCVM_D_U_FAZAA_RIGHT   ,
    P_BKS2_58_BCVM_U_FAZAB_RIGHT     ,
    P_BKS2_58_BCVM_D_U_FAZAB_RIGHT   ,
    P_BKS2_58_BCVM_U_FAZAC_RIGHT     ,
    P_BKS2_58_BCVM_D_U_FAZAC_RIGHT   ,
    P_BKS2_58_BCVM_F_RKANPER_I       ,
    P_BKS2_58_BCVM_D_F_RKANPER_I     ,
    P_BKS2_58_BCVM_U_RIGHTAV_SHIN    ,
    P_BKS2_58_BCVM_D_U_RIGHTAV_SHIN  ,
    P_BKS2_58_BCVM_I_VU2             ,
    P_BKS2_58_BCVM_D_I_VU2           ,
    P_BKS2_58_BCVM_I_VU3             ,
    P_BKS2_58_BCVM_D_I_VU3           ,
    P_BKS2_58_BCVM_T4                ,
    P_BKS2_58_BCVM_D_T4              ,
    P_BKS2_58_BCVM_TNOS_2            ,
    P_BKS2_58_BCVM_D_TNOS_2          ,
    P_BKS2_58_BCVM_TZAK_2            ,
    P_BKS2_58_BCVM_D_TZAK_2          ,
    P_BKS2_58_BCVM_T_BKDU            ,
    P_BKS2_58_BCVM_D_T_BKDU          ,
    P_BKS2_58_BCVM_T_STEKLA2         ,
    P_BKS2_58_BCVM_D_T_STEKLA2       ,
    P_BKS2_58_BCVM_PK_DD4_2          ,
    P_BKS2_58_BCVM_D_PK_DD4_2        ,
    P_BKS2_58_BCVM_UKONTR_EPP        ,
    P_BKS2_58_BCVM_D_UKONTR_EPP      ,
    P_BKS2_58_BCVM_PVK               ,
    P_BKS2_58_BCVM_D_PVK             ,
    P_BKS2_58_BCVM_H_OTNOS           ,
    P_BKS2_58_BCVM_D_H_OTNOS         ,
    P_BKS2_58_BCVM_V_PR              ,
    P_BKS2_58_BCVM_D_V_PR            ,
    P_BKS2_58_BCVM_V_IST             ,
    P_BKS2_58_BCVM_D_V_IST           ,
    P_BKS2_58_BCVM_CISLO_M           ,
    P_BKS2_58_BCVM_D_CISLO_M         ,
    P_BKS2_58_BCVM_DD1_SGO_2         ,
    P_BKS2_58_BCVM_D_DD1_SGO_2       ,
    P_BKS2_58_BCVM_DD2_SGO_2         ,
    P_BKS2_58_BCVM_D_DD2_SGO_2       ,
    P_BKS2_58_BCVM_T_ZA_KOMPR        ,
    P_BKS2_58_BCVM_D_N_SGO_2         ,
    P_BKS2_58_BCVM_T_ZA_RES          ,
    P_BKS2_58_BCVM_D_T_ZA_RES        ,



    P_BKS3_58_BCVM_MVI_SS_3          ,
    P_BKS3_58_BCVM_MPA_SS_3          ,
    P_BKS3_58_BCVM_MPA_SS1_3         ,
    P_BKS3_58_BCVM_MPA_SS2_3         ,
    P_BKS3_58_BCVM_MSK_SS_3          ,
    P_BKS3_58_BCVM_KS_3              ,
    P_BKS3_58_BCVM_SDZU_3            ,
    P_BKS3_58_BCVM_TIMESTART_3       ,
    P_BKS3_58_BCVM_TIMESTOP_3        ,

    P_BKS3_58_BCVM_SCB_3             ,
    P_BKS3_58_BCVM_SDS_11_3          ,
    P_BKS3_58_BCVM_SDS_12_3          ,
    P_BKS3_58_BCVM_SDS_13_3          ,
    P_BKS3_58_BCVM_SDS_14_3          ,
    P_BKS3_58_BCVM_SDS_15_3          ,
    P_BKS3_58_BCVM_SDS_28_3          ,
    P_BKS3_58_BCVM_Operating_Time_3  ,
    P_BKS3_58_BCVM_SJS_BKS_3         ,

    P_BKS3_58_BCVM_P_GA_2GS         ,
    P_BKS3_58_BCVM_D_P_GA_2GS       ,
    P_BKS3_58_BCVM_P_1GS            ,
    P_BKS3_58_BCVM_D_P_1GS          ,
    P_BKS3_58_BCVM_PERSHT_1GS       ,
    P_BKS3_58_BCVM_D_PERSHT_1GS     ,
    P_BKS3_58_BCVM_TRJ_1GS          ,
    P_BKS3_58_BCVM_D_TRJ_1GS        ,
    P_BKS3_58_BCVM_T_SGO_1          ,
    P_BKS3_58_BCVM_D_T_SGO_1        ,
    P_BKS3_58_BCVM_TAIR_ENTERLD     ,
    P_BKS3_58_BCVM_D_TAIR_ENTERLD   ,
    P_BKS3_58_BCVM_OBK_PUP_LD       ,
    P_BKS3_58_BCVM_D_OBK_PUP_LD     ,
    P_BKS3_58_BCVM_TGASTURB_LD      ,
    P_BKS3_58_BCVM_D_TGASTURB_LD    ,
    P_BKS3_58_BCVM_TPODSH1          ,
    P_BKS3_58_BCVM_D_TPODSH1        ,
    P_BKS3_58_BCVM_T_ZA_AT3_1       ,
    P_BKS3_58_BCVM_D_T_ZA_AT3_1     ,
    P_BKS3_58_BCVM_T_FPVD           ,
    P_BKS3_58_BCVM_D_T_FPVD         ,
    P_BKS3_58_BCVM_T_KOST           ,
    P_BKS3_58_BCVM_D_T_KOST         ,
    P_BKS3_58_BCVM_PKOST_DD5        ,
    P_BKS3_58_BCVM_D_PKOST_DD5      ,
    P_BKS3_58_BCVM_NTK              ,
    P_BKS3_58_BCVM_D_NTK            ,
    P_BKS3_58_BCVM_PGOR_DD1_2       ,
    P_BKS3_58_BCVM_D_PGOR_DD1_2     ,
    P_BKS3_58_BCVM_U_PP1_L          ,
    P_BKS3_58_BCVM_D_U_PP1_L        ,
    P_BKS3_58_BCVM_U_PP2_L          ,
    P_BKS3_58_BCVM_D_U_PP2_L        ,


    P_BKS4_58_BCVM_SDS_19_4             ,
    P_BKS4_58_BCVM_SDS_17_4             ,
    P_BKS4_58_BCVM_SDS_18_4             ,
    P_BKS4_58_BCVM_SDS_21_4             ,
    P_BKS4_58_BCVM_SCB_4             ,

    P_BKS4_58_BCVM_Operating_Time_4  ,
    P_BKS4_58_BCVM_SJS_BKS_4         ,

    P_BKS4_58_BCVM_MVI_SS_4          ,
    P_BKS4_58_BCVM_MPA_SS_4          ,
    P_BKS4_58_BCVM_MPA_SS1_4         ,
    P_BKS4_58_BCVM_MPA_SS2_4         ,
    P_BKS4_58_BCVM_MSK_SS_4          ,
    P_BKS4_58_BCVM_KS_4              ,
    P_BKS4_58_BCVM_SDZU_4            ,
    P_BKS4_58_BCVM_TIMESTART_4       ,
    P_BKS4_58_BCVM_TIMESTOP_4        ,

    P_BKS4_58_BCVM_P_GA_1GS          ,
    P_BKS4_58_BCVM_D_P_GA_1GS        ,
    P_BKS4_58_BCVM_P_2GS             ,
    P_BKS4_58_BCVM_D_P_2GS           ,
    P_BKS4_58_BCVM_PERSHT_2GS        ,
    P_BKS4_58_BCVM_D_PERSHT_2GS      ,
    P_BKS4_58_BCVM_TRJ_2GS           ,
    P_BKS4_58_BCVM_D_TRJ_2GS         ,
    P_BKS4_58_BCVM_TAIR_ENTERRD      ,
    P_BKS4_58_BCVM_D_TAIR_ENTERRD    ,
    P_BKS4_58_BCVM_OBK_PUP_RD        ,
    P_BKS4_58_BCVM_D_OBK_PUP_RD      ,
    P_BKS4_58_BCVM_TGASTURB_RD       ,
    P_BKS4_58_BCVM_D_TGASTURB_RD     ,
    P_BKS4_58_BCVM_T_ZA_AT3_2        ,
    P_BKS4_58_BCVM_D_T_ZA_AT3_2      ,
    P_BKS4_58_BCVM_TPODSH2           ,
    P_BKS4_58_BCVM_D_TPODSH2         ,
    P_BKS4_58_BCVM_T_SGO_2           ,
    P_BKS4_58_BCVM_D_T_SGO_2         ,
    P_BKS4_58_BCVM_U_PP1_R           ,
    P_BKS4_58_BCVM_D_U_PP1_R         ,
    P_BKS4_58_BCVM_U_PP2_R           ,
    P_BKS4_58_BCVM_D_U_PP2_R         ,
    P_ARK_STATUS_FARK                ,
    P_ARK_ED_MHZ                     ,
    P_ARK_HUN_KHZ                    ,
    P_ARK_DES_KHZ                    ,
    P_ARK_ED_KHZ                     ,
    P_ARK_VISHE                      ,
    P_ARK_REG                        ,
    P_ARK_KUR                        ,
    P_ARK_STATUS_KUR                 ,
    P_CO2010_BCVM_OTKAZ_SO           ,
    P_CO2010_BCVM_OTKAZ_AFS          ,
    P_CO2010_BCVM_OTKAZ_KLS          ,
    P_CO2010_BCVM_MAT                ,
    P_BUS_5P_SRK1                    ,
    P_BUS_5P_SRK2                    ,
    P_CON_5P_SRK1                    ,
    P_CON_5P_SRK2                    ,
    P_CON_5P_SRK3                    ,
    P_CON_5P_SRK4                    ,
    P_BRPI_SRK1                      ,
    P_BRPI_OMEGA_POL_9TP             ,
    P_BRPI_OMEGA_POL_10TP            ,
    P_BRPI_OMEGA_POL_11TP            ,
    P_BRPI_OMEGA_POL_12TP            ,
    P_BI_M_1_5P_SRK1                 ,
    P_BI_M_1_5P_SRK2                 ,
    P_BI_M_1_5P_SRK3                 ,
    P_BI_M_2_5P_SRK1                 ,
    P_BI_M_2_5P_SRK2                 ,
    P_BI_M_2_5P_SRK3                 ,
    P_BI_M_3_5P_SRK1                 ,
    P_BI_M_3_5P_SRK2                 ,
    P_BI_M_3_5P_SRK3                 ,
    P_BI_M_4_5P_SRK1                 ,
    P_BI_M_4_5P_SRK2                 ,
    P_BI_M_4_5P_SRK3                 ,
    P_BI_M_5_5P_SRK1                 ,
    P_BI_M_5_5P_SRK2                 ,
    P_BI_M_5_5P_SRK3                 ,
    P_BI_M_5_5P_SRK4                 ,
    P_BI_M_5_5P_SRK5                 ,
    P_BI_M_5_5P_SRK6                 ,
    P_BI_M_6_5P_SRK1                 ,
    P_BI_M_6_5P_SRK2                 ,
    P_BI_M_6_5P_SRK3                 ,
    P_BI_M_6_5P_SRK4                 ,
    P_BI_M_6_5P_SRK5                 ,
    P_BI_M_6_5P_SRK6                 ,
    P_BI_M_9_5P_SRK1                 ,
    P_BI_M_9_5P_SRK2                 ,
    P_BI_M_9_5P_SRK3                 ,
    P_BI_M_9_5P_SRK4                 ,
    P_BI_M_9_5P_SRK5                 ,
    P_BI_M_9_5P_SRK6                 ,
    P_BI_M_10_5P_SRK1                ,
    P_BI_M_10_5P_SRK2                ,
    P_BI_M_10_5P_SRK3                ,
    P_BI_M_10_5P_SRK4                ,
    P_BI_M_10_5P_SRK5                ,
    P_BI_M_10_5P_SRK6                ,
    P_BI_M_11_5P_SRK1                ,
    P_BI_M_11_5P_SRK2                ,
    P_BI_M_11_5P_SRK3                ,
    P_BI_M_12_5P_SRK1                ,
    P_BI_M_12_5P_SRK2                ,
    P_BI_M_12_5P_SRK3                ,
    P_BNP_SS                         ,
    P_BNP_SS4                        ,
    P_BNP_DP_A                       ,
    P_BNP_DP_D                       ,
    P_BNP_DP_P                       ,
    P_BNP_DP_D_TD                    ,
    P_BNP_ARM                        ,
    P_BNP_GOT_A                      ,
    P_BNP_DRM                        ,
    P_BNP_WORD3                     ,
    P_BNP_GOT_D                      ,
    P_BNP_GOT_P                      ,
    P_BNP_GOT_D_TD                   ,
    P_BNP_NO_CONTROL                   ,
    P_BNP_MODE_RSBN                  ,
    P_BNP_MODE_PRMG                  ,
    P_BNP_MODE_TACAN                  ,
    P_BNP_MODE_DME_P                  ,
    P_BNP_MODE_DME_N                  ,
    P_BNP_MODE_DME                  ,


    P_BNP_EPS_K                      ,
    P_BNP_GOT_EPS_K                  ,
    P_BNP_EPS_G                      ,
    P_BNP_GOT_EPS_G                  ,
    P_BNP_EPS_R0                     ,
    //P_BNP_GOT_R0                     ,
    P_BNP_DELTA_RPK                  ,
    P_BNP_RAZVOROT                   ,
    P_BNP_GOT_DELTA_RPK              ,
    P_BNP_R0                         ,
    P_BNP_GOT_R0                     ,
    P_BNP_R1                         ,
    P_BNP_GOT_R1                     ,
    P_BNP_R2                         ,
    P_BNP_GOT_R2                     ,
    P_BNP_R3                         ,
    P_BNP_GOT_R3                     ,
    P_BNP_R4                         ,
    P_BNP_GOT_R4                     ,
    P_BNP_R5                         ,
    P_BNP_GOT_R5                     ,
    P_BNP_R6                         ,
    P_BNP_GOT_R6                     ,
    P_BNP_R7                         ,
    P_BNP_GOT_R7                     ,
    P_BNP_R8                         ,
    P_BNP_GOT_R8                     ,
    P_BNP_R9                         ,
    P_BNP_GOT_R9                     ,
    P_BNP_R10                         ,
    P_BNP_GOT_R10                     ,
    P_BNP_R11                         ,
    P_BNP_GOT_R11                     ,

    P_BNP_FI0                         ,
    P_BNP_GOT_FI0                     ,
    P_BNP_FI1                         ,
    P_BNP_GOT_FI1                     ,
    P_BNP_FI2                         ,
    P_BNP_GOT_FI2                     ,
    P_BNP_FI3                         ,
    P_BNP_GOT_FI3                     ,
    P_BNP_FI4                         ,
    P_BNP_GOT_FI4                     ,
    P_BNP_FI5                         ,
    P_BNP_GOT_FI5                     ,
    P_BNP_FI6                         ,
    P_BNP_GOT_FI6                     ,
    P_BNP_FI7                         ,
    P_BNP_GOT_FI7                     ,
    P_BNP_FI8                         ,
    P_BNP_GOT_FI8                     ,
    P_BNP_FI9                         ,
    P_BNP_GOT_FI9                     ,
    P_BNP_FI10                         ,
    P_BNP_GOT_FI10                     ,
    P_BNP_FI11                         ,
    P_BNP_GOT_FI11                     ,

    P_BNP_BETA0                         ,
    P_BNP_GOT_BETA0                     ,
    P_BNP_BETA1                         ,
    P_BNP_GOT_BETA1                     ,
    P_BNP_BETA2                         ,
    P_BNP_GOT_BETA2                     ,
    P_BNP_BETA3                         ,
    P_BNP_GOT_BETA3                     ,
    P_BNP_BETA4                        ,
    P_BNP_GOT_BETA4                     ,
    P_BNP_BETA5                         ,
    P_BNP_GOT_BETA5                     ,
    P_BNP_BETA6                         ,
    P_BNP_GOT_BETA6                     ,
    P_BNP_BETA7                         ,
    P_BNP_GOT_BETA7                     ,
    P_BNP_BETA8                         ,
    P_BNP_GOT_BETA8                     ,
    P_BNP_BETA9                         ,
    P_BNP_GOT_BETA9                     ,
    P_BNP_BETA10                         ,
    P_BNP_GOT_BETA10                     ,
    P_BNP_BETA11                         ,
    P_BNP_GOT_BETA11                     ,

    P_BNP_WN0                     ,
    P_BNP_WE0                     ,
    P_BNP_WN1                     ,
    P_BNP_WE1                     ,
    P_BNP_WN2                     ,
    P_BNP_WE2                     ,
    P_BNP_WN3                     ,
    P_BNP_WE3                     ,
    P_BNP_WN4                     ,
    P_BNP_WE4                     ,
    P_BNP_WN5                     ,
    P_BNP_WE5                     ,
    P_BNP_WN6                     ,
    P_BNP_WE6                     ,
    P_BNP_WN7                     ,
    P_BNP_WE7                     ,
    P_BNP_WN8                     ,
    P_BNP_WE8                     ,
    P_BNP_WN9                     ,
    P_BNP_WE9                     ,
    P_BNP_WN10                    ,
    P_BNP_WE10                    ,
    P_BNP_WN11                    ,
    P_BNP_WE11                    ,

    P_BNP_VY0                     ,
    P_BNP_H0                     ,
    P_BNP_VY1                     ,
    P_BNP_H1                     ,
    P_BNP_VY2                     ,
    P_BNP_H2                     ,
    P_BNP_VY3                     ,
    P_BNP_H3                     ,
    P_BNP_VY4                     ,
    P_BNP_H4                     ,
    P_BNP_VY5                     ,
    P_BNP_H5                     ,
    P_BNP_VY6                     ,
    P_BNP_H6                     ,
    P_BNP_VY7                     ,
    P_BNP_H7                     ,
    P_BNP_VY8                     ,
    P_BNP_H8                     ,
    P_BNP_VY9                     ,
    P_BNP_H9                     ,
    P_BNP_VY10                    ,
    P_BNP_H10                    ,
    P_BNP_VY11                    ,
    P_BNP_H11                    ,


    P_BNP_GOT_WN0                 ,
    P_BNP_GOT_WN1                 ,
    P_BNP_GOT_WN2                 ,
    P_BNP_GOT_WN3                 ,
    P_BNP_GOT_WN4                 ,
    P_BNP_GOT_WN5                 ,
    P_BNP_GOT_WN6                 ,
    P_BNP_GOT_WN7                 ,

    P_BNP_GOT_WE0                 ,
    P_BNP_GOT_WE1                 ,
    P_BNP_GOT_WE2                 ,
    P_BNP_GOT_WE3                 ,
    P_BNP_GOT_WE4                 ,
    P_BNP_GOT_WE5                 ,
    P_BNP_GOT_WE6                 ,
    P_BNP_GOT_WE7                 ,

    P_BNP_GOT_WN8                 ,
    P_BNP_GOT_WN9                 ,
    P_BNP_GOT_WN10                 ,
    P_BNP_GOT_WN11                 ,

    P_BNP_GOT_WE8                 ,
    P_BNP_GOT_WE9                 ,
    P_BNP_GOT_WE10                 ,
    P_BNP_GOT_WE11                ,
    P_BNP_WORD25                    ,
    P_BNP_WORD26                    ,

    //P_BNP_DRM                     ,
    P_BNP_SS3                     ,

    P_BP_ARM                      ,
    P_BP_PR_MRK                     ,
    P_BP_GOT_PRMRK                     ,
    P_BP_EPS_K_KRS                     ,
    P_BP_EPS_K_RGM                     ,
    P_BP_EPS_G_KRS                     ,
    P_BP_EPS_G_RGM                     ,
    P_BP_SRK7                          ,
    P_BP_SS                             ,
    P_BP_WORD1                          ,
    P_BP_WORD2                          ,
    P_BP_WORD3                          ,
    P_BP_WORD4                          ,
    P_BP_WORD5                          ,
    P_BP_WORD6                          ,
    P_BP_WORD7                          ,
    P_BP_WORD8                          ,
    P_COUNT_PARAM                       ,
    P_COUNT_PARAM_M                     ,
    P_ISRP_SRK11                        ,
    P_ISRP_SRK21                        ,
    P_ISRP_SRK31                        ,
    P_ISRP_GAMMA                        ,
    P_ISRP_PSI_GMK                      ,
    P_ISRP_PSI_ZAD                      ,
    P_ISRP_P_ZML_ZAD                    ,
    P_ISRP_DPSI_DEVIAT                  ,
    P_ISRP_DUS_X                        ,
    P_ISRP_DUS_Y                        ,
    P_ISRP_DUS_Z                        ,
    P_ISRP_ACC_X                        ,
    P_ISRP_ACC_Y                        ,
    P_ISRP_ACC_Z                        ,
    P_ISRP_MAGN_X                       ,
    P_ISRP_MAGN_Y                       ,
    P_ISRP_MAGN_Z                       ,
    P_KSS_FREQ_ILS                      ,
    P_KSS_ZAD_NUM_SH_APDD               ,
    P_KSS_NAV_REG                       ,
    P_KSS_NAPR_POSSADKA                 ,
    P_KSS_NAPR_3RD                      ,
    P_KSS_METHOD_IN_MRSH                ,
    P_KSS_NUM_M_MRSH                    ,
    P_KSS_NUM_ISP_MRSH                  ,
    P_KSS_TYPE_KOR                      ,
    P_KSS_HPPM                          ,
    P_KSS_NUMAEROVOZ                    ,
    P_KSS_LAM_ISP_AERO                  ,
    P_KSS_FI_ISP_AERO                   ,
    P_KSS_H_KR_ISP_AERO                 ,
    P_KSS_KURS_ISP_AERO                 ,
    P_KSS_D_ISP_AERO                    ,
    P_KSS_KURS_PR_PPM                   ,
    P_KSS_D_PPM                         ,
    P_KSS_CUR_HOUR                      ,
    P_KSS_CUR_MIN                       ,
    P_KSS_CUR_SEC                       ,
    P_KSS_FI                            ,
    P_KSS_LAM                           ,
    P_KSS_YEAR                          ,
    P_KSS_MOUNTH                        ,
    P_KSS_DAY                           ,
    P_KSS_HOUR                          ,
    P_KSS_MIN                           ,
    P_KSS_SEC                           ,
    P_KSS_REG_S70                       ,
    P_KSS_OTKAZ_NASEM_SOST              ,
    P_KSS_REG_WORK_NC                   ,
    P_KSS_OTKAZ_DMV1                    ,
    P_KSS_OTKAZ_DMV2                    ,
    P_KSS_OTKAZ_VIDEO1                  ,
    P_KSS_OTKAZ_VIDEO2                  ,
    P_KSS_OTKAZ_UPR1                    ,
    P_KSS_OTKAZ_UPR2                    ,
    P_KSS_OTKAZ_CIMSS_AN                ,
    P_KSS_CNT_ISPR                      ,
    P_KSS_NUM_PP_UCOKS_ST               ,
    P_KSS_NUM_PP_UCOKS_ML               ,
    P_KSS_CNT_OBMEN                     ,
    P_KSS_ZAP_CS_IUS                    ,
    P_KSS_VED_SR_POS                    ,
    P_CO2010_KSU_USTP                   ,
    P_CO2010_KSU_H                      ,
    P_CO2010_KSU_SIGN_H                 ,
    P_CO2010_KSU_MAT

};

enum E_PACK
{
    E_P_ANY                      ,
    E_P_AR_H29_L12_S0_M4096      ,
    E_P_MIL_H4_L19_S0_M4096      ,
    E_P_AR_H29_L9_S1_M16384      ,
    E_P_AR_H29_L9_S0_M819_2      ,
    E_P_AR_H29_L9_S0_M2365       ,
    E_P_AR_H29_L9_S0_M2_048      ,
    E_P_AR_H29_L9_S1_M256        ,
    E_P_AR_H29_L9_S1_M512        ,
    E_P_AR_H29_L9_S1_M4096       ,
    E_P_AR_H29_L9_S1_M2_048      ,
    E_P_AR_H29_L9_S0_M16384      ,
    E_P_AR_H29_L9_S1_M819_2      ,
    E_P_AR_H29_L9_S0_M409_6      ,
    E_P_AR_H29_L9_S0_M0          ,
    E_P_AR_H29_L9_S0_M4096       ,
    E_P_AR_H31_L30_S0_M0         ,
    E_P_MIL_H4_L19_S1_MMPI       ,
    E_P_MIL_H4_L19_S1_M180       ,
    E_P_AR_H29_L11_S1_M11993_088 ,
    E_P_AR_H29_L15_S1_M512       ,
    E_P_AR_H15_L9_S0_M0          ,
    E_P_AR_H28_L11_S0_M16384_2   ,
    E_P_AR_H28_L11_S0_M7_86432   ,
    E_P_MIL_H4_L19_S1_M819_2     ,
    E_P_MIL_H4_L19_S1_M2048      ,
    E_P_MIL_H4_L19_S1_M2_048     ,
    E_P_MIL_H4_L19_S1_M256       ,
    E_P_MIL_H4_L19_S1_M16384     ,
    E_P_MIL_H4_L19_S1_M64        ,
    E_P_MIL_H4_L19_S1_M512       ,
    E_P_MIL_H4_L19_S1_M90        ,
    E_P_MIL_H4_L19_S1_M8         ,
    E_P_MIL_H4_L19_S1_M4         ,
    E_P_MIL_H4_L19_S1_M812       ,
    E_P_MIL_H4_L19_S0_M0         ,
    E_P_MIL_H4_L19_S1_M32        ,
    E_P_AR_H29_L14_S0_M0         ,
    E_P_MIL_H4_L35_S1_M842_8658  ,
    E_P_MIL_H4_L32_S1_M90        ,
    E_P_MIL_H4_L8_S0_M0          ,
    E_P_MIL_H4_L14_S0_M0         ,
    E_P_MIL_H4_L9_S0_M0          ,
    E_P_MIL_H4_L16_S0_M4096      ,
    E_P_MIL_H4_L16_S0_M163_84    ,
    E_P_MIL_H4_L16_S0_M2_4576    ,
    E_P_MIL_H4_L9_S0_M32         ,
    E_P_MIL_H4_L9_S0_M0_48       ,
    E_P_MIL_H5_L12_S0_M128       ,
    E_P_MIL_H4_L13_S0_M0_512     ,
    E_P_MIL_H4_L14_S0_M1024      ,
    E_P_AR_H18_L15_S0_M0         ,
    E_P_AR_H22_L19_S0_M0         ,
    E_P_AR_H26_L23_S0_M0         ,
    E_P_AR_H29_L27_S0_M0         ,
    E_P_AR_H28_L17_S1_M0_2       ,
    E_P_AR_H28_L17_S1_M0_4       ,
    E_P_MIL_H4_L18_S1_M64        ,
    E_P_MIL_H5_L18_S0_M128       ,
    E_P_MIL_H5_L18_S0_M256       ,
    E_P_MIL_H4_L18_S1_M32        ,
    E_P_MIL_H5_L18_S0_M16        ,
    E_P_MIL_H4_L18_S1_M128       ,
    E_P_MIL_H4_L18_S1_M0_125     ,
    E_P_AR_H29_L14_S1_M16384     ,
    E_P_AR_H29_L14_S1_M819_2     ,
    E_P_AR_H29_L14_S1_M2048      ,
    E_P_AR_H29_L14_S1_M2_048     ,
    E_P_AR_H29_L14_S1_M256       ,
    E_P_AR_H29_L14_S1_M90        ,
    E_P_MIL_H4_L35_S1_MMPI       ,
    E_P_MIL_H4_L19_S0_M32760     ,
    E_P_MIL_H4_L8_S1_M16384      ,
    E_P_MIL_H4_L19_S1_M842_865   ,
    E_P_MIL_H9_L14_S0_M0         ,
    E_P_MIL_H4_L19_S0_M3276_8    ,
    E_P_MIL_H4_L23_S0_M0_5       ,
    E_P_MIL_H4_L19_S0_M842_865   ,
    E_P_MIL_H5_L18_S0_M64        ,
    E_P_AR_H12_L11_S0_M0         ,
    E_P_AR_H14_L13_S0_M0         ,
    E_P_AR_H29_L15_S0_M0         ,
    E_P_AR_H29_L11_S1_M8         ,
    E_P_AR_H29_L9_S1_M65536      ,
    E_P_AR_H29_L14_S1_M512       ,
    E_P_AR_H29_L11_S1_M90        ,
    E_P_AR_H29_L11_S1_M1024      ,
    E_P_AR_H29_L18_S1_M0_0000858 ,
    E_P_AR_H29_L12_S1_M8         ,
    E_P_AR_H29_L11_S1_M16384     ,
    E_P_AR_H29_L11_S1_M2048      ,
    E_P_AR_H29_L11_S0_M0         ,
    E_P_AR_H29_L9_S1_M90         ,
    E_P_AR_H28_L11_S0_M16384     ,
    E_P_AR_H29_L17_S1_M0_2       ,
    E_P_AR_H29_L17_S1_M0_4       ,
    E_P_AR_H28_L11_S1_M7_86432   ,
    E_P_AR_H29_L13_S1_M256       ,
    E_P_AR_H29_L0_S0_M0          ,
    E_P_AR_H28_L16_S0_M4096      ,
    E_P_AR_H28_L16_S0_M163_84    ,
    E_P_AR_H28_L16_S0_M128       ,
    E_P_AR_H28_L16_S0_M2_4576    ,
    E_P_AR_H28_L16_S0_M32        ,
    E_P_AR_H28_L16_S0_M1024      ,
    E_P_AR_H28_L15_S0_M256       ,
    E_P_AR_H28_L15_S0_M0_125     ,
    E_P_MIL_H5_L18_S0_M4096      ,
    E_P_MIL_H5_L18_S0_M4         ,
    E_P_MIL_H5_L18_S0_M32        ,
    E_P_MIL_H5_L18_S0_M1         ,
    E_P_MIL_H5_L18_S0_M1024      ,
    E_P_MIL_H5_L18_S0_M512      ,
    E_P_MIL_H5_L19_S0_M512       ,
    E_P_MIL_H4_L19_S1_M128       ,
    E_P_MIL_H5_L19_S0_M256       ,
    E_P_MIL_H4_L35_S0_M0         ,
    E_P_AR_H28_L14_S0_M512       ,
    E_P_AR_H28_L1_S0_M0          ,
    E_P_AR_H29_L14_S1_M32        ,
    //new
    E_P_AR_H28_L14_S0_M819_2     ,
    E_P_AR_H28_L14_S0_M2_048     ,
    E_P_AR_H29_L14_S1_M8         ,
    E_P_AR_H29_L14_S1_M4         ,
    E_P_AR_H28_L14_S0_M0         ,
    E_P_AR_H29_L14_S1_M2         ,
    E_P_AR_H29_L14_S1_M0_5       ,
    E_P_AR_H29_L14_S1_M1         ,
    E_P_AR_H28_L14_S0_M190       ,
    E_P_AR_H29_L15_S1_M64        ,
    E_P_AR_H29_L15_S1_M0_125     ,
    E_P_AR_H31_L1_S0_M0          ,
    E_P_MIL_H4_L18_S0_M0         ,
    //E_P_MIL_H4_L35_S0_M0         ,
    E_P_MIL_H4_L11_S0_M0         ,
    E_P_MIL_H5_L19_S0_M190       ,
    E_P_MIL_H4_L19_S1_M6        ,
    E_P_MIL_H5_L19_S0_M32       ,
    E_P_MIL_H5_L19_S0_M16       ,
    E_P_AR_H28_L12_S0_M0        ,
    E_P_MIL_H4_L35_S1_M180      ,
    E_P_AR_H29_L14_S1_M81_92    ,
    E_P_AR_H29_L14_S1_M4096     ,
    E_P_AR_H29_L14_S0_M2048     ,
    E_P_AR_H29_L14_S1_M64       ,
    E_P_AR_H29_L14_S0_M2        ,
    E_P_MIL_H7_L14_S0_M0        ,
    E_P_AR_H29_L14_S1_M842_865  ,
    E_P_MIL_H5_L19_S0_M128      ,
    E_P_AR_H29_L17_S1_M90       ,
    E_P_AR_H28_L9_S0_M64        ,
    E_P_AR_H28_L9_S0_M512       ,
    E_P_AR_H24_L9_S0_M0         ,
    E_P_AR_H28_L19_S0_M64       ,
    E_P_AR_H29_L19_S1_M256      ,
    E_P_AR_H28_L19_S0_M128      ,
    //E_P_MIL_H5_L19_S0_M512      ,
    E_P_MIL_H5_L11_S0_M64       ,
    E_P_AR_H29_L14_S1_M1024     ,
    E_P_MIL_H4_L16_S0_M32       ,
    E_P_MIL_H4_L19_S1_M0_5      ,
    E_P_MIL_H4_L19_S1_M1024     ,
    E_P_MIL_H4_L19_S1_M2        ,
    E_P_MIL_H4_L19_S1_M40       ,
    E_P_MIL_H4_L19_S1_M20       ,
    E_P_MIL_H4_L19_S1_M190      ,
    E_P_MIL_H4_L19_S1_M16       ,
    E_P_MIL_H4_L19_S1_M5        ,
    E_P_MIL_H4_L19_S1_M8192     ,
    E_P_MIL_H4_L19_S1_M160      ,
    E_P_MIL_H4_L15_S1_M64       ,
    E_P_AR_H31_L9_S0_M0         ,
    E_P_AR_H29_L14_S1_M40       ,
    E_P_AR_H29_L14_S1_M20       ,
    E_P_AR_H28_L11_S0_M0        ,
    E_P_AR_H31_L14_S0_M0        ,
    E_P_AR_H29_L14_S1_M0        ,
    E_P_AR_H29_L14_S1_M431_16   ,
    E_P_AR_H29_L14_S1_M40_02    ,
    E_P_AR_H29_L14_S1_M1233_73  ,
    E_P_AR_H29_L14_S1_M259_36   ,
    E_P_AR_H29_L14_S1_431_16    ,
    E_P_AR_H30_L9_S1_M16384     ,
    E_P_AR_H30_L9_S1_M819_2     ,
    E_P_AR_H30_L9_S1_M2365      ,
    E_P_AR_H30_L9_S1_M2_048     ,
    E_P_AR_H30_L9_S1_M256       ,
    E_P_AR_H30_L9_S1_M4096      ,
    E_P_AR_H30_L9_S1_M409_6     ,
    E_P_AR_H30_L9_S1_M512       ,
    E_P_MIL_H4_L16_S1_M90       ,
    E_P_MIL_H4_L18_S0_M250000   ,
    E_P_MIL_H4_L16_S1_M42_53    ,
    E_P_MIL_H4_L16_S1_M75_38    ,
    E_P_MIL_H4_L17_S0_M250000   ,
    //E_P_MIL_H4_L16_S1_M42_53    ,
    E_P_MIL_H17_L18_S0_M0       ,
    E_P_AR_H29_L14_S1_M6        ,
    E_P_AR_H29_L14_S1_M16       ,
    E_P_AR_H29_L18_S0_M102_4    ,
    E_P_AR_H29_L25_S0_M0        ,
    E_P_AR_H29_L26_S0_M0        ,
    E_P_AR_H25_L19_S0_M0        ,
    E_P_AR_H18_L16_S0_M0        ,
    E_P_AR_H14_L9_S0_M0         ,
    E_P_AR_H29_L9_S1_M_PI_2     ,
    E_P_AR_H29_L19_S0_M0        ,
    E_P_AR_H29_L21_S0_M0        ,
    E_P_AR_H20_L12_S0_M25_6     ,
    E_P_AR_H29_L14_S0_M180      ,
    E_P_AR_H29_L16_S0_M81_92    ,
    E_P_AR_H24_L19_S0_M0        ,
    E_P_AR_H18_L13_S0_M0        ,
    E_P_AR_H29_L14_S1_M_PI_2    ,
    E_P_AR_H29_L23_S0_M0        ,
    E_P_AR_H18_L14_S0_M0        ,
    //E_P_AR_H29_L25_S0_M0        ,
    //E_P_AR_H24_L19_S0_M0        ,
    //E_P_AR_H18_L13_S0_M0        ,
    //E_P_AR_H29_L26_S0_M0        ,
    E_P_AR_H21_L14_S0_M0        ,
    E_P_MIL_H4_L7_S0_M0         ,
    E_P_MIL_H4_L19_S1_M_PI_2    ,
    E_P_MIL_H4_L10_S0_M0        ,
    E_P_MIL_H11_L14_S0_M0       ,
    E_P_MIL_H15_L19_S0_M0       ,
    E_P_MIL_H4_L15_S0_M102_4    ,
    E_P_MIL_H8_L14_S0_M0        ,
    E_P_MIL_H15_L17_S0_M0       ,
    E_P_MIL_H4_L24_S1_M_PI      ,
    E_P_MIL_H4_L12_S0_M0        ,
    E_P_MIL_H4_L12_S0_M25_6     ,
    E_P_MIL_H4_L19_S0_M180      ,
    E_P_MIL_H4_L17_S0_M81_92    ,
    E_P_MIL_H4_L6_S0_M0         ,
    E_P_AR_H32_L1_S0_M0         ,
    E_P_AR_H29_L1_S0_M0         ,
    //E_P_MIL_H18_L5_S0_M64
    E_P_AR_H29_L14_S1_M190


};
#endif // CHDEV_H
